NeXusJavaBindings: ncsa.hdf.hdflib.HDFNativeData Class Reference
ncsa.hdf.hdflib.HDFNativeData Class Reference
Public Member Functions
HDFNativeData ()
Object byteToNumber (byte[] barray, Object obj) throws HDFException
Static Public Member Functions
static native int[] byteToInt (byte[] data)
static native float[] byteToFloat (byte[] data)
static native short[] byteToShort (byte[] data)
static native long[] byteToLong (byte[] data)
static native double[] byteToDouble (byte[] data)
static native int[] byteToInt (int start, int len, byte[] data)
static int byteToInt (byte[] data, int start)
static native short[] byteToShort (int start, int len, byte[] data)
static short byteToShort (byte[] data, int start)
static native float[] byteToFloat (int start, int len, byte[] data)
static float byteToFloat (byte[] data, int start)
static native long[] byteToLong (int start, int len, byte[] data)
static long byteToLong (byte[] data, int start)
static native double[] byteToDouble (int start, int len, byte[] data)
static double byteToDouble (byte[] data, int start)
static native byte[] intToByte (int start, int len, int[] data)
static native byte[] shortToByte (int start, int len, short[] data)
static native byte[] floatToByte (int start, int len, float[] data)
static native byte[] longToByte (int start, int len, long[] data)
static native byte[] doubleToByte (int start, int len, double[] data)
static native byte[] byteToByte (byte data)
static native byte[] intToByte (int data)
static native byte[] shortToByte (short data)
static native byte[] floatToByte (float data)
static native byte[] longToByte (long data)
static native byte[] doubleToByte (double data)
static Object defineDataObject (int dataType, int datasize)
Allocate a 1D array large enough to hold a multidimensional array of 'datasize' elements of 'dataType' numbers.
Detailed Description
Definition at line 14 of file HDFNativeData.java.
Constructor & Destructor Documentation
ncsa.hdf.hdflib.HDFNativeData.HDFNativeData ()
Definition at line 16 of file HDFNativeData.java.
Member Function Documentation
static native byte [] ncsa.hdf.hdflib.HDFNativeData.byteToByte (byte data) static
static native double [] ncsa.hdf.hdflib.HDFNativeData.byteToDouble (byte[] data) static
Referenced by ncsa.hdf.hdflib.HDFNativeData.byteToDouble().
static native double [] ncsa.hdf.hdflib.HDFNativeData.byteToDouble (int start, int len, byte[] data) static
static double ncsa.hdf.hdflib.HDFNativeData.byteToDouble (byte[] data, int start) static
Definition at line 56 of file HDFNativeData.java.
References ncsa.hdf.hdflib.HDFNativeData.byteToDouble().
static native float [] ncsa.hdf.hdflib.HDFNativeData.byteToFloat (byte[] data) static
Referenced by ncsa.hdf.hdflib.HDFNativeData.byteToFloat().
static native float [] ncsa.hdf.hdflib.HDFNativeData.byteToFloat (int start, int len, byte[] data) static
static float ncsa.hdf.hdflib.HDFNativeData.byteToFloat (byte[] data, int start) static
Definition at line 40 of file HDFNativeData.java.
References ncsa.hdf.hdflib.HDFNativeData.byteToFloat().
static native int [] ncsa.hdf.hdflib.HDFNativeData.byteToInt (byte[] data) static
Referenced by ncsa.hdf.hdflib.HDFNativeData.byteToInt().
static native int [] ncsa.hdf.hdflib.HDFNativeData.byteToInt (int start, int len, byte[] data) static
static int ncsa.hdf.hdflib.HDFNativeData.byteToInt (byte[] data, int start) static
Definition at line 24 of file HDFNativeData.java.
References ncsa.hdf.hdflib.HDFNativeData.byteToInt().
static native long [] ncsa.hdf.hdflib.HDFNativeData.byteToLong (byte[] data) static
Referenced by ncsa.hdf.hdflib.HDFNativeData.byteToLong().
static native long [] ncsa.hdf.hdflib.HDFNativeData.byteToLong (int start, int len, byte[] data) static
static long ncsa.hdf.hdflib.HDFNativeData.byteToLong (byte[] data, int start) static
Definition at line 48 of file HDFNativeData.java.
References ncsa.hdf.hdflib.HDFNativeData.byteToLong().
Object ncsa.hdf.hdflib.HDFNativeData.byteToNumber (byte[] barray, Object obj) throws HDFException
Definition at line 82 of file HDFNativeData.java.
static native short [] ncsa.hdf.hdflib.HDFNativeData.byteToShort (byte[] data) static
Referenced by ncsa.hdf.hdflib.HDFNativeData.byteToShort().
static native short [] ncsa.hdf.hdflib.HDFNativeData.byteToShort (int start, int len, byte[] data) static
static short ncsa.hdf.hdflib.HDFNativeData.byteToShort (byte[] data, int start) static
Definition at line 32 of file HDFNativeData.java.
References ncsa.hdf.hdflib.HDFNativeData.byteToShort().
static Object ncsa.hdf.hdflib.HDFNativeData.defineDataObject (int dataType, int datasize) static
Allocate a 1D array large enough to hold a multidimensional array of 'datasize' elements of 'dataType' numbers.
This is called from ncsa.hdf.hdfobject.HDFGR and ncsa.hdf.hdfobject.HDFSDS, and hdf.ncsa.io.ASCII2HDF
Parameters:
dataType the type of the iamge data
datasize the size of the image data array
Returns:
an array of 'datasize' numbers of 'dataType
See also:
ncsa.hdf.hdfobject.HDFGR
ncsa.hdf.hdfobject.HDFSDS
Definition at line 128 of file HDFNativeData.java.
References ncsa.hdf.hdflib.HDFConstants.DFNT_CHAR, ncsa.hdf.hdflib.HDFConstants.DFNT_FLOAT32, ncsa.hdf.hdflib.HDFConstants.DFNT_FLOAT64, ncsa.hdf.hdflib.HDFConstants.DFNT_INT16, ncsa.hdf.hdflib.HDFConstants.DFNT_INT32, ncsa.hdf.hdflib.HDFConstants.DFNT_INT64, ncsa.hdf.hdflib.HDFConstants.DFNT_INT8, ncsa.hdf.hdflib.HDFConstants.DFNT_LITEND, ncsa.hdf.hdflib.HDFConstants.DFNT_UCHAR8, ncsa.hdf.hdflib.HDFConstants.DFNT_UINT16, ncsa.hdf.hdflib.HDFConstants.DFNT_UINT32, ncsa.hdf.hdflib.HDFConstants.DFNT_UINT64, and ncsa.hdf.hdflib.HDFConstants.DFNT_UINT8.
static native byte [] ncsa.hdf.hdflib.HDFNativeData.doubleToByte (int start, int len, double[] data) static
static native byte [] ncsa.hdf.hdflib.HDFNativeData.doubleToByte (double data) static
static native byte [] ncsa.hdf.hdflib.HDFNativeData.floatToByte (int start, int len, float[] data) static
static native byte [] ncsa.hdf.hdflib.HDFNativeData.floatToByte (float data) static
static native byte [] ncsa.hdf.hdflib.HDFNativeData.intToByte (int start, int len, int[] data) static
static native byte [] ncsa.hdf.hdflib.HDFNativeData.intToByte (int data) static
static native byte [] ncsa.hdf.hdflib.HDFNativeData.longToByte (int start, int len, long[] data) static
static native byte [] ncsa.hdf.hdflib.HDFNativeData.longToByte (long data) static
static native byte [] ncsa.hdf.hdflib.HDFNativeData.shortToByte (int start, int len, short[] data) static
static native byte [] ncsa.hdf.hdflib.HDFNativeData.shortToByte (short data) static
The documentation for this class was generated from the following file:
bindings/java/ncsa/hdf/hdflib/HDFNativeData.java