NeXusJavaBindings: bindings/java/native/hdfnativeImp.c File Reference
hdfnativeImp.c File Reference
#include <stdio.h>
#include "jni.h"
#include "hdfexceptionImp.h"
Typedefs
typedef int intn
Functions
JNIEXPORT jintArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToInt___3B (JNIEnv *env, jclass class, jbyteArray bdata)
JNIEXPORT jfloatArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToFloat___3B (JNIEnv *env, jclass class, jbyteArray bdata)
JNIEXPORT jshortArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToShort___3B (JNIEnv *env, jclass class, jbyteArray bdata)
JNIEXPORT jlongArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToLong___3B (JNIEnv *env, jclass class, jbyteArray bdata)
JNIEXPORT jdoubleArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToDouble___3B (JNIEnv *env, jclass class, jbyteArray bdata)
JNIEXPORT jintArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToInt__II_3B (JNIEnv *env, jclass class, jint start, jint len, jbyteArray bdata)
JNIEXPORT jshortArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToShort__II_3B (JNIEnv *env, jclass class, jint start, jint len, jbyteArray bdata)
JNIEXPORT jfloatArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToFloat__II_3B (JNIEnv *env, jclass class, jint start, jint len, jbyteArray bdata)
JNIEXPORT jlongArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToLong__II_3B (JNIEnv *env, jclass class, jint start, jint len, jbyteArray bdata)
JNIEXPORT jdoubleArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToDouble__II_3B (JNIEnv *env, jclass class, jint start, jint len, jbyteArray bdata)
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_intToByte__II_3I (JNIEnv *env, jclass class, jint start, jint len, jintArray idata)
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_shortToByte__II_3S (JNIEnv *env, jclass class, jint start, jint len, jshortArray idata)
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_floatToByte__II_3F (JNIEnv *env, jclass class, jint start, jint len, jfloatArray idata)
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_doubleToByte__II_3D (JNIEnv *env, jclass class, jint start, jint len, jdoubleArray idata)
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_longToByte__II_3J (JNIEnv *env, jclass class, jint start, jint len, jlongArray idata)
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_intToByte__I (JNIEnv *env, jclass class, jint idata)
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_floatToByte__F (JNIEnv *env, jclass class, jfloat idata)
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_shortToByte__S (JNIEnv *env, jclass class, jshort idata)
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_doubleToByte__D (JNIEnv *env, jclass class, jdouble idata)
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_longToByte__J (JNIEnv *env, jclass class, jlong idata)
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToByte__B (JNIEnv *env, jclass class, jbyte idata)
Typedef Documentation
typedef int intn
Definition at line 35 of file hdfnativeImp.c.
Function Documentation
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToByte__B (JNIEnv * env, jclass class, jbyte idata)
Definition at line 1222 of file hdfnativeImp.c.
References JNIFatalError(), and outOfMemory().
JNIEXPORT jdoubleArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToDouble___3B (JNIEnv * env, jclass class, jbyteArray bdata)
Definition at line 273 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jdoubleArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToDouble__II_3B (JNIEnv * env, jclass class, jint start, jint len, jbyteArray bdata)
Definition at line 587 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jfloatArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToFloat___3B (JNIEnv * env, jclass class, jbyteArray bdata)
Definition at line 101 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jfloatArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToFloat__II_3B (JNIEnv * env, jclass class, jint start, jint len, jbyteArray bdata)
Definition at line 458 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jintArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToInt___3B (JNIEnv * env, jclass class, jbyteArray bdata)
Definition at line 42 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jintArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToInt__II_3B (JNIEnv * env, jclass class, jint start, jint len, jbyteArray bdata)
Definition at line 330 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jlongArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToLong___3B (JNIEnv * env, jclass class, jbyteArray bdata)
Definition at line 216 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jlongArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToLong__II_3B (JNIEnv * env, jclass class, jint start, jint len, jbyteArray bdata)
Definition at line 522 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jshortArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToShort___3B (JNIEnv * env, jclass class, jbyteArray bdata)
Definition at line 157 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jshortArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_byteToShort__II_3B (JNIEnv * env, jclass class, jint start, jint len, jbyteArray bdata)
Definition at line 394 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_doubleToByte__D (JNIEnv * env, jclass class, jdouble idata)
Definition at line 1140 of file hdfnativeImp.c.
References JNIFatalError(), and outOfMemory().
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_doubleToByte__II_3D (JNIEnv * env, jclass class, jint start, jint len, jdoubleArray idata)
Definition at line 869 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_floatToByte__F (JNIEnv * env, jclass class, jfloat idata)
Definition at line 1058 of file hdfnativeImp.c.
References JNIFatalError(), and outOfMemory().
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_floatToByte__II_3F (JNIEnv * env, jclass class, jint start, jint len, jfloatArray idata)
Definition at line 796 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_intToByte__I (JNIEnv * env, jclass class, jint idata)
Definition at line 1018 of file hdfnativeImp.c.
References JNIFatalError(), and outOfMemory().
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_intToByte__II_3I (JNIEnv * env, jclass class, jint start, jint len, jintArray idata)
Definition at line 650 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_longToByte__II_3J (JNIEnv * env, jclass class, jint start, jint len, jlongArray idata)
Definition at line 943 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_longToByte__J (JNIEnv * env, jclass class, jlong idata)
Definition at line 1181 of file hdfnativeImp.c.
References JNIFatalError(), and outOfMemory().
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_shortToByte__II_3S (JNIEnv * env, jclass class, jint start, jint len, jshortArray idata)
Definition at line 723 of file hdfnativeImp.c.
References JNIFatalError(), outOfMemory(), and raiseException().
JNIEXPORT jbyteArray JNICALL Java_ncsa_hdf_hdflib_HDFNativeData_shortToByte__S (JNIEnv * env, jclass class, jshort idata)
Definition at line 1098 of file hdfnativeImp.c.
References JNIFatalError(), and outOfMemory().