NeXusJavaBindings: bindings/java/native/NexusFile.c File Reference
NexusFile.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <string.h>
#include "org_nexusformat_NexusFile.h"
#include <napi.h>
#include "handle.h"
Functions
JNIEXPORT jint JNICALL JNI_OnLoad (JavaVM *vm, void *reserved)
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_init (JNIEnv *env, jobject obj, jstring filename, jint access)
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nxflush (JNIEnv *env, jobject obj, jint handle)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_close (JNIEnv *env, jobject obj, jint handle)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakegroup (JNIEnv *env, jobject obj, jint handle, jstring name, jstring nxclass)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopengroup (JNIEnv *env, jobject obj, jint handle, jstring name, jstring nxclass)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopenpath (JNIEnv *env, jobject obj, jint handle, jstring path)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopengrouppath (JNIEnv *env, jobject obj, jint handle, jstring path)
JNIEXPORT jstring JNICALL Java_org_nexusformat_NexusFile_nxgetpath (JNIEnv *env, jobject obj, jint handle)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxclosegroup (JNIEnv *env, jobject obj, jint handle)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakedata (JNIEnv *env, jobject obj, jint handle, jstring name, jint type, jint rank, jintArray dim)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakedata64 (JNIEnv *env, jobject obj, jint handle, jstring name, jint type, jint rank, jlongArray dim)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakecompdata (JNIEnv *env, jobject obj, jint handle, jstring name, jint type, jint rank, jintArray dim, jint compression_type, jintArray chunk)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakecompdata64 (JNIEnv *env, jobject obj, jint handle, jstring name, jint type, jint rank, jlongArray dim, jint compression_type, jlongArray chunk)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopendata (JNIEnv *env, jobject obj, jint handle, jstring name)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxclosedata (JNIEnv *env, jobject obj, jint handle)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxcompress (JNIEnv *env, jobject obj, jint handle, jint comp_type)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputdata (JNIEnv *env, jobject obj, jint handle, jbyteArray data)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputslab (JNIEnv *env, jobject obj, jint handle, jbyteArray data, jintArray start, jintArray end)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputslab64 (JNIEnv *env, jobject obj, jint handle, jbyteArray data, jlongArray start, jlongArray end)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputattr (JNIEnv *env, jobject obj, jint handle, jstring name, jbyteArray data, jint type)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetdata (JNIEnv *env, jobject obj, jint handle, jbyteArray data)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetslab (JNIEnv *env, jobject obj, jint handle, jintArray start, jintArray end, jbyteArray data)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetslab64 (JNIEnv *env, jobject obj, jint handle, jlongArray start, jlongArray end, jbyteArray data)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetattr (JNIEnv *env, jobject obj, jint handle, jstring name, jbyteArray data, jintArray args)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetgroupid (JNIEnv *env, jobject obj, jint handle, jobject linki)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetdataid (JNIEnv *env, jobject obj, jint handle, jobject linki)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakelink (JNIEnv *env, jobject obj, jint handle, jobject target)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakenamedlink (JNIEnv *env, jobject obj, jint handle, jstring name, jobject target)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopensourcegroup (JNIEnv *env, jobject obj, jint handle)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxsetnumberformat (JNIEnv *env, jobject obj, jint handle, jint type, jstring format)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetinfo (JNIEnv *env, jobject obj, jint handle, jintArray dim, jintArray args)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetinfo64 (JNIEnv *env, jobject obj, jint handle, jlongArray dim, jintArray args)
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nextentry (JNIEnv *env, jobject obj, jint handle, jobjectArray jnames)
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nextattr (JNIEnv *env, jobject obj, jint handle, jobjectArray jnames, jintArray args)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxinquirefile (JNIEnv *env, jobject obj, jint handle, jobjectArray jnames)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxlinkexternal (JNIEnv *env, jobject obj, jint handle, jstring name, jstring nxclass, jstring nxurl)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxlinkexternaldataset (JNIEnv *env, jobject obj, jint handle, jstring name, jstring nxurl)
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nxisexternalgroup (JNIEnv *env, jobject obj, jint handle, jstring name, jstring nxclass, jobjectArray jnames)
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nxisexternaldataset (JNIEnv *env, jobject obj, jint handle, jstring name, jobjectArray jnames)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_initattrdir (JNIEnv *env, jobject obj, jint handle)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_initgroupdir (JNIEnv *env, jobject obj, jint handle)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_debugstop (JNIEnv *env, jobject obj)
Function Documentation
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_close (JNIEnv * env, jobject obj, jint handle)
Definition at line 155 of file NexusFile.c.
References HHGetPointer(), and HHRemoveHandle().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_debugstop (JNIEnv * env, jobject obj)
Definition at line 1580 of file NexusFile.c.
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_init (JNIEnv * env, jobject obj, jstring filename, jint access)
Definition at line 87 of file NexusFile.c.
References HHMakeHandle().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_initattrdir (JNIEnv * env, jobject obj, jint handle)
Definition at line 1543 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_initgroupdir (JNIEnv * env, jobject obj, jint handle)
Definition at line 1560 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nextattr (JNIEnv * env, jobject obj, jint handle, jobjectArray jnames, jintArray args)
Definition at line 1382 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nextentry (JNIEnv * env, jobject obj, jint handle, jobjectArray jnames)
Definition at line 1354 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxclosedata (JNIEnv * env, jobject obj, jint handle)
Definition at line 532 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxclosegroup (JNIEnv * env, jobject obj, jint handle)
Definition at line 337 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxcompress (JNIEnv * env, jobject obj, jint handle, jint comp_type)
Definition at line 551 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nxflush (JNIEnv * env, jobject obj, jint handle)
Definition at line 125 of file NexusFile.c.
References HHGetPointer(), HHMakeHandle(), and HHRemoveHandle().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetattr (JNIEnv * env, jobject obj, jint handle, jstring name, jbyteArray data, jintArray args)
Definition at line 835 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetdata (JNIEnv * env, jobject obj, jint handle, jbyteArray data)
Definition at line 735 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetdataid (JNIEnv * env, jobject obj, jint handle, jobject linki)
Definition at line 968 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetgroupid (JNIEnv * env, jobject obj, jint handle, jobject linki)
Definition at line 885 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetinfo (JNIEnv * env, jobject obj, jint handle, jintArray dim, jintArray args)
Definition at line 1283 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetinfo64 (JNIEnv * env, jobject obj, jint handle, jlongArray dim, jintArray args)
Definition at line 1317 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT jstring JNICALL Java_org_nexusformat_NexusFile_nxgetpath (JNIEnv * env, jobject obj, jint handle)
Definition at line 314 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetslab (JNIEnv * env, jobject obj, jint handle, jintArray start, jintArray end, jbyteArray data)
Definition at line 767 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetslab64 (JNIEnv * env, jobject obj, jint handle, jlongArray start, jlongArray end, jbyteArray data)
Definition at line 801 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxinquirefile (JNIEnv * env, jobject obj, jint handle, jobjectArray jnames)
Definition at line 1409 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nxisexternaldataset (JNIEnv * env, jobject obj, jint handle, jstring name, jobjectArray jnames)
Definition at line 1515 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nxisexternalgroup (JNIEnv * env, jobject obj, jint handle, jstring name, jstring nxclass, jobjectArray jnames)
Definition at line 1484 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxlinkexternal (JNIEnv * env, jobject obj, jint handle, jstring name, jstring nxclass, jstring nxurl)
Definition at line 1429 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxlinkexternaldataset (JNIEnv * env, jobject obj, jint handle, jstring name, jstring nxurl)
Definition at line 1458 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakecompdata (JNIEnv * env, jobject obj, jint handle, jstring name, jint type, jint rank, jintArray dim, jint compression_type, jintArray chunk)
Definition at line 424 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakecompdata64 (JNIEnv * env, jobject obj, jint handle, jstring name, jint type, jint rank, jlongArray dim, jint compression_type, jlongArray chunk)
Definition at line 464 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakedata (JNIEnv * env, jobject obj, jint handle, jstring name, jint type, jint rank, jintArray dim)
Definition at line 356 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakedata64 (JNIEnv * env, jobject obj, jint handle, jstring name, jint type, jint rank, jlongArray dim)
Definition at line 390 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakegroup (JNIEnv * env, jobject obj, jint handle, jstring name, jstring nxclass)
Definition at line 182 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakelink (JNIEnv * env, jobject obj, jint handle, jobject target)
Definition at line 1051 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakenamedlink (JNIEnv * env, jobject obj, jint handle, jstring name, jobject target)
Definition at line 1138 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopendata (JNIEnv * env, jobject obj, jint handle, jstring name)
Definition at line 504 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopengroup (JNIEnv * env, jobject obj, jint handle, jstring name, jstring nxclass)
Definition at line 212 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopengrouppath (JNIEnv * env, jobject obj, jint handle, jstring path)
Definition at line 282 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopenpath (JNIEnv * env, jobject obj, jint handle, jstring path)
Definition at line 248 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopensourcegroup (JNIEnv * env, jobject obj, jint handle)
Definition at line 1230 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputattr (JNIEnv * env, jobject obj, jint handle, jstring name, jbyteArray data, jint type)
Definition at line 676 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputdata (JNIEnv * env, jobject obj, jint handle, jbyteArray data)
Definition at line 574 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputslab (JNIEnv * env, jobject obj, jint handle, jbyteArray data, jintArray start, jintArray end)
Definition at line 606 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputslab64 (JNIEnv * env, jobject obj, jint handle, jbyteArray data, jlongArray start, jlongArray end)
Definition at line 641 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxsetnumberformat (JNIEnv * env, jobject obj, jint handle, jint type, jstring format)
Definition at line 1249 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT jint JNICALL JNI_OnLoad (JavaVM * vm, void * reserved)
Definition at line 37 of file NexusFile.c.