NeXusJavaBindings: bindings/java/native/org_nexusformat_NexusFile.h File Reference
org_nexusformat_NexusFile.h File Reference
#include <jni.h>
Macros
#define org_nexusformat_NexusFile_NXACC_READ 1L
#define org_nexusformat_NexusFile_NXACC_RDWR 2L
#define org_nexusformat_NexusFile_NXACC_CREATE 3L
#define org_nexusformat_NexusFile_NXACC_CREATE4 4L
#define org_nexusformat_NexusFile_NXACC_CREATE5 5L
#define org_nexusformat_NexusFile_NXACC_CREATEXML 6L
#define org_nexusformat_NexusFile_NXACC_NOSTRIP 128L
#define org_nexusformat_NexusFile_NX_UNLIMITED -1L
#define org_nexusformat_NexusFile_NX_FLOAT32 5L
#define org_nexusformat_NexusFile_NX_FLOAT64 6L
#define org_nexusformat_NexusFile_NX_INT8 20L
#define org_nexusformat_NexusFile_NX_BINARY 20L
#define org_nexusformat_NexusFile_NX_UINT8 21L
#define org_nexusformat_NexusFile_NX_BOOLEAN 21L
#define org_nexusformat_NexusFile_NX_INT16 22L
#define org_nexusformat_NexusFile_NX_UINT16 23L
#define org_nexusformat_NexusFile_NX_INT32 24L
#define org_nexusformat_NexusFile_NX_UINT32 25L
#define org_nexusformat_NexusFile_NX_INT64 26L
#define org_nexusformat_NexusFile_NX_UINT64 27L
#define org_nexusformat_NexusFile_NX_CHAR 4L
#define org_nexusformat_NexusFile_NX_COMP_NONE 100L
#define org_nexusformat_NexusFile_NX_COMP_LZW 200L
#define org_nexusformat_NexusFile_NX_COMP_RLE 300L
#define org_nexusformat_NexusFile_NX_COMP_HUF 400L
#define org_nexusformat_NexusFile_MAXNAMELEN 64L
Functions
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_init (JNIEnv *, jobject, jstring, jint)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_close (JNIEnv *, jobject, jint)
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nxflush (JNIEnv *, jobject, jint)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakegroup (JNIEnv *, jobject, jint, jstring, jstring)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopengroup (JNIEnv *, jobject, jint, jstring, jstring)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopenpath (JNIEnv *, jobject, jint, jstring)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopengrouppath (JNIEnv *, jobject, jint, jstring)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxclosegroup (JNIEnv *, jobject, jint)
JNIEXPORT jstring JNICALL Java_org_nexusformat_NexusFile_nxgetpath (JNIEnv *, jobject, jint)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakedata (JNIEnv *, jobject, jint, jstring, jint, jint, jintArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakedata64 (JNIEnv *, jobject, jint, jstring, jint, jint, jlongArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakecompdata (JNIEnv *, jobject, jint, jstring, jint, jint, jintArray, jint, jintArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakecompdata64 (JNIEnv *, jobject, jint, jstring, jint, jint, jlongArray, jint, jlongArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopendata (JNIEnv *, jobject, jint, jstring)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxclosedata (JNIEnv *, jobject, jint)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxcompress (JNIEnv *, jobject, jint, jint)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetdata (JNIEnv *, jobject, jint, jbyteArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetslab (JNIEnv *, jobject, jint, jintArray, jintArray, jbyteArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetslab64 (JNIEnv *, jobject, jint, jlongArray, jlongArray, jbyteArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetattr (JNIEnv *, jobject, jint, jstring, jbyteArray, jintArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputdata (JNIEnv *, jobject, jint, jbyteArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputslab (JNIEnv *, jobject, jint, jbyteArray, jintArray, jintArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputslab64 (JNIEnv *, jobject, jint, jbyteArray, jlongArray, jlongArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputattr (JNIEnv *, jobject, jint, jstring, jbyteArray, jint)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetinfo (JNIEnv *, jobject, jint, jintArray, jintArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetinfo64 (JNIEnv *, jobject, jint, jlongArray, jintArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxsetnumberformat (JNIEnv *, jobject, jint, jint, jstring)
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nextentry (JNIEnv *, jobject, jint, jobjectArray)
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nextattr (JNIEnv *, jobject, jint, jobjectArray, jintArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_initattrdir (JNIEnv *, jobject, jint)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_initgroupdir (JNIEnv *, jobject, jint)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetgroupid (JNIEnv *, jobject, jint, jobject)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetdataid (JNIEnv *, jobject, jint, jobject)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakelink (JNIEnv *, jobject, jint, jobject)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakenamedlink (JNIEnv *, jobject, jint, jstring, jobject)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopensourcepath (JNIEnv *, jobject, jint)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxinquirefile (JNIEnv *, jobject, jint, jobjectArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxlinkexternal (JNIEnv *, jobject, jint, jstring, jstring, jstring)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxlinkexternaldataset (JNIEnv *, jobject, jint, jstring, jstring)
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nxisexternalgroup (JNIEnv *, jobject, jint, jstring, jstring, jobjectArray)
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nxisexternaldataset (JNIEnv *, jobject, jint, jstring, jobjectArray)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_debugstop (JNIEnv *, jobject)
Macro Definition Documentation
#define org_nexusformat_NexusFile_MAXNAMELEN 64L
Definition at line 61 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_BINARY 20L
Definition at line 33 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_BOOLEAN 21L
Definition at line 37 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_CHAR 4L
Definition at line 51 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_COMP_HUF 400L
Definition at line 59 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_COMP_LZW 200L
Definition at line 55 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_COMP_NONE 100L
Definition at line 53 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_COMP_RLE 300L
Definition at line 57 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_FLOAT32 5L
Definition at line 27 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_FLOAT64 6L
Definition at line 29 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_INT16 22L
Definition at line 39 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_INT32 24L
Definition at line 43 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_INT64 26L
Definition at line 47 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_INT8 20L
Definition at line 31 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_UINT16 23L
Definition at line 41 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_UINT32 25L
Definition at line 45 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_UINT64 27L
Definition at line 49 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_UINT8 21L
Definition at line 35 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NX_UNLIMITED -1L
Definition at line 25 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NXACC_CREATE 3L
Definition at line 15 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NXACC_CREATE4 4L
Definition at line 17 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NXACC_CREATE5 5L
Definition at line 19 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NXACC_CREATEXML 6L
Definition at line 21 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NXACC_NOSTRIP 128L
Definition at line 23 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NXACC_RDWR 2L
Definition at line 13 of file org_nexusformat_NexusFile.h.
#define org_nexusformat_NexusFile_NXACC_READ 1L
Definition at line 11 of file org_nexusformat_NexusFile.h.
Function Documentation
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_close (JNIEnv * , jobject , jint)
Definition at line 155 of file NexusFile.c.
References HHGetPointer(), and HHRemoveHandle().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_debugstop (JNIEnv * , jobject)
Definition at line 1580 of file NexusFile.c.
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_init (JNIEnv * , jobject , jstring , jint)
Definition at line 87 of file NexusFile.c.
References HHMakeHandle().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_initattrdir (JNIEnv * , jobject , jint)
Definition at line 1543 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_initgroupdir (JNIEnv * , jobject , jint)
Definition at line 1560 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nextattr (JNIEnv * , jobject , jint , jobjectArray , jintArray)
Definition at line 1382 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nextentry (JNIEnv * , jobject , jint , jobjectArray)
Definition at line 1354 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxclosedata (JNIEnv * , jobject , jint)
Definition at line 532 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxclosegroup (JNIEnv * , jobject , jint)
Definition at line 337 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxcompress (JNIEnv * , jobject , jint , jint)
Definition at line 551 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nxflush (JNIEnv * , jobject , jint)
Definition at line 125 of file NexusFile.c.
References HHGetPointer(), HHMakeHandle(), and HHRemoveHandle().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetattr (JNIEnv * , jobject , jint , jstring , jbyteArray , jintArray)
Definition at line 835 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetdata (JNIEnv * , jobject , jint , jbyteArray)
Definition at line 735 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetdataid (JNIEnv * , jobject , jint , jobject)
Definition at line 968 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetgroupid (JNIEnv * , jobject , jint , jobject)
Definition at line 885 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetinfo (JNIEnv * , jobject , jint , jintArray , jintArray)
Definition at line 1283 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetinfo64 (JNIEnv * , jobject , jint , jlongArray , jintArray)
Definition at line 1317 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT jstring JNICALL Java_org_nexusformat_NexusFile_nxgetpath (JNIEnv * , jobject , jint)
Definition at line 314 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetslab (JNIEnv * , jobject , jint , jintArray , jintArray , jbyteArray)
Definition at line 767 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxgetslab64 (JNIEnv * , jobject , jint , jlongArray , jlongArray , jbyteArray)
Definition at line 801 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxinquirefile (JNIEnv * , jobject , jint , jobjectArray)
Definition at line 1409 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nxisexternaldataset (JNIEnv * , jobject , jint , jstring , jobjectArray)
Definition at line 1515 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT jint JNICALL Java_org_nexusformat_NexusFile_nxisexternalgroup (JNIEnv * , jobject , jint , jstring , jstring , jobjectArray)
Definition at line 1484 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxlinkexternal (JNIEnv * , jobject , jint , jstring , jstring , jstring)
Definition at line 1429 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxlinkexternaldataset (JNIEnv * , jobject , jint , jstring , jstring)
Definition at line 1458 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakecompdata (JNIEnv * , jobject , jint , jstring , jint , jint , jintArray , jint , jintArray)
Definition at line 424 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakecompdata64 (JNIEnv * , jobject , jint , jstring , jint , jint , jlongArray , jint , jlongArray)
Definition at line 464 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakedata (JNIEnv * , jobject , jint , jstring , jint , jint , jintArray)
Definition at line 356 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakedata64 (JNIEnv * , jobject , jint , jstring , jint , jint , jlongArray)
Definition at line 390 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakegroup (JNIEnv * , jobject , jint , jstring , jstring)
Definition at line 182 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakelink (JNIEnv * , jobject , jint , jobject)
Definition at line 1051 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxmakenamedlink (JNIEnv * , jobject , jint , jstring , jobject)
Definition at line 1138 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopendata (JNIEnv * , jobject , jint , jstring)
Definition at line 504 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopengroup (JNIEnv * , jobject , jint , jstring , jstring)
Definition at line 212 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopengrouppath (JNIEnv * , jobject , jint , jstring)
Definition at line 282 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopenpath (JNIEnv * , jobject , jint , jstring)
Definition at line 248 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxopensourcepath (JNIEnv * , jobject , jint)
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputattr (JNIEnv * , jobject , jint , jstring , jbyteArray , jint)
Definition at line 676 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputdata (JNIEnv * , jobject , jint , jbyteArray)
Definition at line 574 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputslab (JNIEnv * , jobject , jint , jbyteArray , jintArray , jintArray)
Definition at line 606 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxputslab64 (JNIEnv * , jobject , jint , jbyteArray , jlongArray , jlongArray)
Definition at line 641 of file NexusFile.c.
References HHGetPointer().
JNIEXPORT void JNICALL Java_org_nexusformat_NexusFile_nxsetnumberformat (JNIEnv * , jobject , jint , jint , jstring)
Definition at line 1249 of file NexusFile.c.
References HHGetPointer().