#ifndef QCEPDATAOBJECTGRAPHCONTROLLERPTR_H
#define QCEPDATAOBJECTGRAPHCONTROLLERPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QcepDataObjectGraphController)

#endif // QCEPDATAOBJECTGRAPHCONTROLLERPTR_H

