#ifndef QCEPSETRANGEOFIMAGECOMMANDPTR_H
#define QCEPSETRANGEOFIMAGECOMMANDPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QcepSetRangeOfImageCommand)

#endif // QCEPSETRANGEOFIMAGECOMMANDPTR_H
