#ifndef QCEPSETDATAVALUERANGECOMMANDPTR_H
#define QCEPSETDATAVALUERANGECOMMANDPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QcepSetDataValueRangeCommand)

#endif // QCEPSETDATAVALUERANGECOMMANDPTR_H
