NeXus: nxumodule Module Reference
nxumodule Module Reference
Data Types
interface nxureaddata
interface nxuwritedata
Public Member Functions
integer function, public nxuwriteglobals (file_id, user, affiliation, address, phone, fax, email)
integer function, public nxuwritegroup (file_id, group_name, group_class)
integer function nxuwritei4 (file_id, data_name, data, units)
integer function nxuwriter4 (file_id, data_name, data, units)
integer function nxuwriter8 (file_id, data_name, data, units)
integer function nxuwritechar (file_id, data_name, data, units)
integer function nxuwritei4array (file_id, data_name, data, units, data_start, data_size)
integer function nxuwriter4array (file_id, data_name, data, units, data_start, data_size)
integer function nxuwriter8array (file_id, data_name, data, units, data_start, data_size)
integer function nxuwrite2di4array (file_id, data_name, data, units, data_start, data_size)
integer function nxuwrite2dr4array (file_id, data_name, data, units, data_start, data_size)
integer function nxuwrite2dr8array (file_id, data_name, data, units, data_start, data_size)
integer function nxuwrite3di4array (file_id, data_name, data, units, data_start, data_size)
integer function nxuwrite3dr4array (file_id, data_name, data, units, data_start, data_size)
integer function nxuwrite3dr8array (file_id, data_name, data, units, data_start, data_size)
integer function nxureadi4 (file_id, data_name, data, units)
integer function nxureadr4 (file_id, data_name, data, units)
integer function nxureadr8 (file_id, data_name, data, units)
integer function nxureadchar (file_id, data_name, data, units)
integer function nxureadi4array (file_id, data_name, data, units, data_start, data_size)
integer function nxureadr4array (file_id, data_name, data, units, data_start, data_size)
integer function nxureadr8array (file_id, data_name, data, units, data_start, data_size)
integer function nxuread2di4array (file_id, data_name, data, units, data_start, data_size)
integer function nxuread2dr4array (file_id, data_name, data, units, data_start, data_size)
integer function nxuread2dr8array (file_id, data_name, data, units, data_start, data_size)
integer function nxuread3di4array (file_id, data_name, data, units, data_start, data_size)
integer function nxuread3dr4array (file_id, data_name, data, units, data_start, data_size)
integer function nxuread3dr8array (file_id, data_name, data, units, data_start, data_size)
integer function, public nxusetcompress (file_id, compress_type, compress_size)
integer function, public nxufindgroup (file_id, group_name, group_class)
integer function, public nxufindclass (file_id, group_class, group_name, find_index)
integer function, public nxufinddata (file_id, data_name)
integer function, public nxufindattr (file_id, attr_name)
integer function, public nxufindsignal (file_id, signal, data_name, data_rank, data_type, data_dimensions)
integer function, public nxufindaxis (file_id, axis, primary, data_name, data_type, data_dimensions)
integer function, public nxufindlink (file_id, group_id, group_class)
integer function, public nxuresumelink (file_id, group_id)
Detailed Description
Definition at line 27 of file NXUmodule.f90.
Member Function/Subroutine Documentation
integer function, public nxumodule::nxufindattr (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) attr_name)
Definition at line 983 of file NXUmodule.f90.
References nxmodule::nxattrdir(), nxmodule::nxerror(), and nxmodule::nxgetattrinfo().
Referenced by nxufindaxis(), nxufindsignal(), nxuwrite2di4array(), nxuwrite2dr4array(), nxuwrite2dr8array(), nxuwrite3di4array(), nxuwrite3dr4array(), nxuwrite3dr8array(), nxuwritechar(), nxuwritei4(), nxuwritei4array(), nxuwriter4(), nxuwriter4array(), nxuwriter8(), and nxuwriter8array().
integer function, public nxumodule::nxufindaxis (type(nxhandle), intent(inout) file_id, integer, intent(in) axis, integer, intent(in) primary, character(len=*) data_name, integer, intent(out) data_type, integer, dimension(nx_maxrank), intent(out) data_dimensions)
Definition at line 1059 of file NXUmodule.f90.
References nxmodule::nxerror(), nxmodule::nxgetinfo(), nxmodule::nxgetnextentry(), nxmodule::nxinitgroupdir(), nxmodule::nxopendata(), nxufindattr(), and nxufindsignal().
integer function, public nxumodule::nxufindclass (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) group_class, character(len=*), intent(out) group_name, integer, intent(in), optional find_index)
Definition at line 909 of file NXUmodule.f90.
References nxmodule::nxerror(), nxmodule::nxgetgroupinfo(), and nxmodule::nxgroupdir().
integer function, public nxumodule::nxufinddata (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name)
Definition at line 948 of file NXUmodule.f90.
References nxmodule::nxerror(), nxmodule::nxgetgroupinfo(), and nxmodule::nxgroupdir().
Referenced by nxuresumelink().
integer function, public nxumodule::nxufindgroup (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) group_name, character(len=*), intent(out), optional group_class)
Definition at line 872 of file NXUmodule.f90.
References nxmodule::nxerror(), nxmodule::nxgetgroupinfo(), and nxmodule::nxgroupdir().
integer function, public nxumodule::nxufindlink (type(nxhandle), intent(inout) file_id, type(nxlink), intent(out) group_id, character(len=*), intent(in), optional group_class)
Definition at line 1170 of file NXUmodule.f90.
References nxmodule::nxclosegroup(), nxmodule::nxgetdataid(), and nxmodule::nxgetgroupid().
integer function, public nxumodule::nxufindsignal (type(nxhandle), intent(inout) file_id, integer, intent(in) signal, character(len=*) data_name, integer, intent(out) data_rank, integer, intent(out) data_type, integer, dimension(:), intent(out) data_dimensions)
Definition at line 1010 of file NXUmodule.f90.
References nxmodule::nxerror(), nxmodule::nxgetinfo(), nxmodule::nxgetnextentry(), nxmodule::nxinitgroupdir(), nxmodule::nxopendata(), and nxufindattr().
Referenced by nxufindaxis().
integer function nxumodule::nxuread2di4array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, integer(kind=nxi4), dimension(:,:), pointer data, character(len=*), intent(out), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 628 of file NXUmodule.f90.
integer function nxumodule::nxuread2dr4array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr4), dimension(:,:), pointer data, character(len=*), intent(out), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 665 of file NXUmodule.f90.
integer function nxumodule::nxuread2dr8array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr8), dimension(:,:), pointer data, character(len=*), intent(out), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 702 of file NXUmodule.f90.
integer function nxumodule::nxuread3di4array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, integer(kind=nxi4), dimension(:,:,:), pointer data, character(len=*), intent(out), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 739 of file NXUmodule.f90.
integer function nxumodule::nxuread3dr4array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr4), dimension(:,:,:), pointer data, character(len=*), intent(out), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 776 of file NXUmodule.f90.
integer function nxumodule::nxuread3dr8array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr8), dimension(:,:,:), pointer data, character(len=*), intent(out), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 813 of file NXUmodule.f90.
integer function nxumodule::nxureadchar (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, character(len=*), intent(out) data, character(len=*), intent(out), optional units)
Definition at line 528 of file NXUmodule.f90.
integer function nxumodule::nxureadi4 (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, integer(kind=nxi4), intent(out) data, character(len=*), intent(out), optional units)
Definition at line 450 of file NXUmodule.f90.
integer function nxumodule::nxureadi4array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, integer(kind=nxi4), dimension(:), pointer data, character(len=*), intent(out), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 550 of file NXUmodule.f90.
integer function nxumodule::nxureadr4 (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr4), intent(out) data, character(len=*), intent(out), optional units)
Definition at line 476 of file NXUmodule.f90.
integer function nxumodule::nxureadr4array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr4), dimension(:), pointer data, character(len=*), intent(out), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 576 of file NXUmodule.f90.
integer function nxumodule::nxureadr8 (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr8), intent(out) data, character(len=*), intent(out), optional units)
Definition at line 502 of file NXUmodule.f90.
integer function nxumodule::nxureadr8array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr8), dimension(:), pointer data, character(len=*), intent(out), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 602 of file NXUmodule.f90.
integer function, public nxumodule::nxuresumelink (type(nxhandle), intent(inout) file_id, type(nxlink), intent(in) group_id)
Definition at line 1193 of file NXUmodule.f90.
References nxmodule::nxclosedata(), nxmodule::nxclosegroup(), nxmodule::nxerror(), nxmodule::nxgetdataid(), nxmodule::nxgetgroupid(), nxmodule::nxgetgroupinfo(), nxmodule::nxgetinfo(), nxmodule::nxgroupdir(), nxmodule::nxmakedata(), nxmodule::nxopendata(), nxmodule::nxopengroup(), nxmodule::nxsameid(), and nxufinddata().
integer function, public nxumodule::nxusetcompress (type(nxhandle), intent(inout) file_id, integer, intent(in) compress_type, integer, intent(in), optional compress_size)
Definition at line 851 of file NXUmodule.f90.
References nxmodule::nxerror().
integer function nxumodule::nxuwrite2di4array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, integer(kind=nxi4), dimension(:,:), intent(in) data, character(len=*), intent(in), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 272 of file NXUmodule.f90.
References nxufindattr().
integer function nxumodule::nxuwrite2dr4array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr4), dimension(:,:), intent(in) data, character(len=*), intent(in), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 301 of file NXUmodule.f90.
References nxufindattr().
integer function nxumodule::nxuwrite2dr8array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr8), dimension(:,:), intent(in) data, character(len=*), intent(in), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 330 of file NXUmodule.f90.
References nxufindattr().
integer function nxumodule::nxuwrite3di4array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, integer(kind=nxi4), dimension(:,:,:), intent(in) data, character(len=*), intent(in), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 359 of file NXUmodule.f90.
References nxufindattr().
integer function nxumodule::nxuwrite3dr4array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr4), dimension(:,:,:), intent(in) data, character(len=*), intent(in), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 388 of file NXUmodule.f90.
References nxufindattr().
integer function nxumodule::nxuwrite3dr8array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr8), dimension(:,:,:), intent(in) data, character(len=*), intent(in), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 417 of file NXUmodule.f90.
References nxufindattr().
integer function nxumodule::nxuwritechar (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, character(len=*), intent(in) data, character(len=*), intent(in), optional units)
Definition at line 175 of file NXUmodule.f90.
References nxufindattr().
integer function, public nxumodule::nxuwriteglobals (type(nxhandle), intent(in) file_id, character(len=*), intent(in), optional user, character(len=*), intent(in), optional affiliation, character(len=*), intent(in), optional address, character(len=*), intent(in), optional phone, character(len=*), intent(in), optional fax, character(len=*), intent(in), optional email)
Definition at line 64 of file NXUmodule.f90.
integer function, public nxumodule::nxuwritegroup (type(nxhandle), intent(in) file_id, character(len=*), intent(in) group_name, character(len=*), intent(in) group_class)
Definition at line 100 of file NXUmodule.f90.
References nxmodule::nxmakegroup(), and nxmodule::nxopengroup().
integer function nxumodule::nxuwritei4 (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, integer(kind=nxi4), intent(in) data, character(len=*), intent(in), optional units)
Definition at line 118 of file NXUmodule.f90.
References nxufindattr().
integer function nxumodule::nxuwritei4array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, integer(kind=nxi4), dimension(:), intent(in) data, character(len=*), intent(in), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 195 of file NXUmodule.f90.
References nxufindattr().
integer function nxumodule::nxuwriter4 (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr4), intent(in) data, character(len=*), intent(in), optional units)
Definition at line 137 of file NXUmodule.f90.
References nxufindattr().
integer function nxumodule::nxuwriter4array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr4), dimension(:), intent(in) data, character(len=*), intent(in), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 220 of file NXUmodule.f90.
References nxufindattr().
integer function nxumodule::nxuwriter8 (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr8), intent(in) data, character(len=*), intent(in), optional units)
Definition at line 156 of file NXUmodule.f90.
References nxufindattr().
integer function nxumodule::nxuwriter8array (type(nxhandle), intent(inout) file_id, character(len=*), intent(in) data_name, real(kind=nxr8), dimension(:), intent(in) data, character(len=*), intent(in), optional units, integer, dimension(:), intent(in), optional data_start, integer, dimension(:), intent(in), optional data_size)
Definition at line 246 of file NXUmodule.f90.
References nxufindattr().
The documentation for this module was generated from the following file:
bindings/f90/NXUmodule.f90