NeXus: nxmodule Module Reference
nxmodule Module Reference
Data Types
interface nxgetattr
interface nxgetdata
interface nxgetslab
type nxhandle
type nxlink
interface nxputattr
interface nxputdata
interface nxputslab
Public Member Functions
integer function, public nxopen (file_name, access_method, file_id)
integer function, public nxclose (file_id)
integer function, public nxflush (file_id)
integer function, public nxmakegroup (file_id, group_name, group_class)
integer function, public nxopengroup (file_id, group_name, group_class)
integer function, public nxclosegroup (file_id)
integer function, public nxmakedata (file_id, data_name, data_type, data_rank, data_dimensions, compress_type, chunk_size)
integer function, public nxopendata (file_id, data_name)
integer function, public nxcompress (file_id, compress_type)
integer function, public nxclosedata (file_id)
integer function nxgeti1 (file_id, data)
integer function nxgeti2 (file_id, data)
integer function nxgeti4 (file_id, data)
integer function nxgetr4 (file_id, data)
integer function nxgetr8 (file_id, data)
integer function nxgetchar (file_id, data)
integer function nxgeti1slab (file_id, data, data_start, data_size)
integer function nxgeti2slab (file_id, data, data_start, data_size)
integer function nxgeti4slab (file_id, data, data_start, data_size)
integer function nxgetr4slab (file_id, data, data_start, data_size)
integer function nxgetr8slab (file_id, data, data_start, data_size)
integer function nxgeti1attr (file_id, attr_name, value, attr_length, attr_type)
integer function nxgeti2attr (file_id, attr_name, value, attr_length, attr_type)
integer function nxgeti4attr (file_id, attr_name, value, attr_length, attr_type)
integer function nxgetr4attr (file_id, attr_name, value, attr_length, attr_type)
integer function nxgetr8attr (file_id, attr_name, value, attr_length, attr_type)
integer function nxgetcharattr (file_id, attr_name, value, attr_length, attr_type)
integer function nxputi1 (file_id, data)
integer function nxputi2 (file_id, data)
integer function nxputi4 (file_id, data)
integer function nxputr4 (file_id, data)
integer function nxputr8 (file_id, data)
integer function nxputchar (file_id, data)
integer function nxputi1slab (file_id, data, data_start, data_size)
integer function nxputi2slab (file_id, data, data_start, data_size)
integer function nxputi4slab (file_id, data, data_start, data_size)
integer function nxputr4slab (file_id, data, data_start, data_size)
integer function nxputr8slab (file_id, data, data_start, data_size)
integer function nxputi1attr (file_id, name, value, value_length, value_type)
integer function nxputi2attr (file_id, name, value, value_length, value_type)
integer function nxputi4attr (file_id, name, value, value_length, value_type)
integer function nxputr4attr (file_id, name, value, value_length, value_type)
integer function nxputr8attr (file_id, name, value, value_length, value_type)
integer function nxputcharattr (file_id, name, value, value_length, value_type)
integer function, public nxgetinfo (file_id, data_rank, data_dimensions, data_type)
integer function, public nxgetnextentry (file_id, name, class, data_type)
integer function, public nxgetnextattr (file_id, attr_name, attr_length, attr_type)
integer function, public nxgetgroupid (file_id, group_id)
integer function, public nxgetdataid (file_id, data_id)
logical function, public nxsameid (file_id, first_id, second_id)
integer function, public nxmakelink (file_id, link)
integer function, public nxgetgroupinfo (file_id, item_number, group_name, group_class)
integer function, public nxinitgroupdir (file_id)
integer function, public nxgroupdir (file_id, item_number, item_name, item_class)
integer function, public nxgetattrinfo (file_id, attr_number)
integer function, public nxinitattrdir (file_id)
integer function, public nxattrdir (file_id, attr_number, attr_name)
integer function, dimension(size(dimensions)),
public nxreverse (rank, dimensions)
integer(kind=nxi1) function,
dimension(255), public nxcstring (string)
character(len=255) function, public nxfstring (array)
character(len=10) function, public nxdatatype (int_type)
subroutine, public nxerror (message)
Public Attributes
character(len=*), parameter, public nexus_version = "2.0.1"
integer, parameter, public nxacc_read = 1
integer, parameter, public nxacc_rdwr = 2
integer, parameter, public nxacc_create = 3
integer, parameter, public nxacc_create4 = 4
integer, parameter, public nxacc_create5 = 5
integer, parameter, public nx_ok = 1
integer, parameter, public nx_error = 0
integer, parameter, public nx_eod = -1
integer, parameter, public nx_char = 4
integer, parameter, public nx_float32 = 5
integer, parameter, public nx_float64 = 6
integer, parameter, public nx_int8 = 20
integer, parameter, public nx_uint8 = 21
integer, parameter, public nx_int16 = 22
integer, parameter, public nx_uint16 = 23
integer, parameter, public nx_int32 = 24
integer, parameter, public nx_uint32 = 25
integer, parameter, public nx_comp_none = 100
integer, parameter, public nx_comp_lzw = 200
integer, parameter, public nx_comp_rle = 300
integer, parameter, public nx_comp_huf = 400
integer, parameter, public nx_unlimited = -1
integer, parameter, public nx_maxrank = 32
integer, parameter, public nx_maxnamelen = 64
integer, parameter, public nx_maxstack = 20
integer, parameter, public nxi1 = selected_int_kind(2)
integer, parameter, public nxi2 = selected_int_kind(4)
integer, parameter, public nxi4 = selected_int_kind(8)
integer, parameter, public nxr4 = kind(1.0)
integer, parameter, public nxr8 = kind(1.0D0)
Detailed Description
Definition at line 27 of file NXmodule.f90.
Member Function/Subroutine Documentation
integer function, public nxmodule::nxattrdir (type(nxhandle), intent(inout) file_id, integer, intent(out) attr_number, character(len=*), dimension(:) attr_name)
Definition at line 1271 of file NXmodule.f90.
References nxerror(), nxgetnextattr(), and nxinitattrdir().
Referenced by nxumodule::nxufindattr().
integer function, public nxmodule::nxclose (type(nxhandle), intent(in) file_id)
Definition at line 137 of file NXmodule.f90.
integer function, public nxmodule::nxclosedata (type(nxhandle), intent(in) file_id)
Definition at line 251 of file NXmodule.f90.
Referenced by nxumodule::nxuresumelink().
integer function, public nxmodule::nxclosegroup (type(nxhandle), intent(in) file_id)
Definition at line 185 of file NXmodule.f90.
Referenced by nxumodule::nxufindlink(), and nxumodule::nxuresumelink().
integer function, public nxmodule::nxcompress (type(nxhandle), intent(in) file_id, integer, intent(in) compress_type)
Definition at line 239 of file NXmodule.f90.
integer(kind=nxi1) function, dimension(255), public nxmodule::nxcstring (character(len=*), intent(in) string)
Definition at line 1317 of file NXmodule.f90.
Referenced by nxgetcharattr(), nxgeti1attr(), nxgeti2attr(), nxgeti4attr(), nxgetr4attr(), nxgetr8attr(), nxmakedata(), nxmakegroup(), nxopen(), nxopendata(), nxopengroup(), nxputchar(), nxputcharattr(), nxputi1attr(), nxputi2attr(), nxputi4attr(), nxputr4attr(), and nxputr8attr().
character(len=10) function, public nxmodule::nxdatatype (integer, intent(in) int_type)
Definition at line 1346 of file NXmodule.f90.
subroutine, public nxmodule::nxerror (character(len=*), intent(in) message)
Definition at line 1365 of file NXmodule.f90.
Referenced by nxattrdir(), nxgetchar(), nxgeti1(), nxgeti1slab(), nxgeti2(), nxgeti2slab(), nxgeti4(), nxgeti4slab(), nxgetr4(), nxgetr4slab(), nxgetr8(), nxgetr8slab(), nxgroupdir(), nxumodule::nxufindattr(), nxumodule::nxufindaxis(), nxumodule::nxufindclass(), nxumodule::nxufinddata(), nxumodule::nxufindgroup(), nxumodule::nxufindsignal(), nxumodule::nxuresumelink(), and nxumodule::nxusetcompress().
integer function, public nxmodule::nxflush (type(nxhandle), intent(inout) file_id)
Definition at line 148 of file NXmodule.f90.
character(len=255) function, public nxmodule::nxfstring (integer(kind=nxi1), dimension(:), intent(in) array)
Definition at line 1331 of file NXmodule.f90.
Referenced by nxgetchar(), nxgetcharattr(), nxgetgroupinfo(), nxgetnextattr(), and nxgetnextentry().
integer function, public nxmodule::nxgetattrinfo (type(nxhandle), intent(inout) file_id, integer, intent(out) attr_number)
Definition at line 1248 of file NXmodule.f90.
Referenced by nxumodule::nxufindattr().
integer function nxmodule::nxgetchar (type(nxhandle), intent(in) file_id, character(len=*), intent(out) data)
Definition at line 461 of file NXmodule.f90.
References nxerror(), nxfstring(), and nxgetinfo().
integer function nxmodule::nxgetcharattr (type(nxhandle), intent(in) file_id, character(len=*), intent(in) attr_name, character(len=*), intent(out) value, integer, intent(inout), optional attr_length, integer, intent(in), optional attr_type)
Definition at line 799 of file NXmodule.f90.
References nxcstring(), and nxfstring().
integer function, public nxmodule::nxgetdataid (type(nxhandle), intent(in) file_id, type(nxlink), intent(out) data_id)
Definition at line 1139 of file NXmodule.f90.
Referenced by nxumodule::nxufindlink(), and nxumodule::nxuresumelink().
integer function, public nxmodule::nxgetgroupid (type(nxhandle), intent(in) file_id, type(nxlink), intent(out) group_id)
Definition at line 1125 of file NXmodule.f90.
Referenced by nxumodule::nxufindlink(), and nxumodule::nxuresumelink().
integer function, public nxmodule::nxgetgroupinfo (type(nxhandle), intent(in) file_id, integer, intent(out) item_number, character(len=*), intent(out), optional group_name, character(len=*), intent(out), optional group_class)
Definition at line 1183 of file NXmodule.f90.
References nxfstring().
Referenced by nxumodule::nxufindclass(), nxumodule::nxufinddata(), nxumodule::nxufindgroup(), and nxumodule::nxuresumelink().
integer function nxmodule::nxgeti1 (type(nxhandle), intent(in) file_id, integer(kind=nxi1), dimension(:), intent(out) data)
Definition at line 266 of file NXmodule.f90.
References nxerror(), and nxgetinfo().
integer function nxmodule::nxgeti1attr (type(nxhandle), intent(in) file_id, character(len=*), intent(in) attr_name, integer(kind=nxi1), intent(out) value, integer, intent(inout), optional attr_length, integer, intent(in), optional attr_type)
Definition at line 709 of file NXmodule.f90.
References nxcstring().
integer function nxmodule::nxgeti1slab (type(nxhandle), intent(in) file_id, integer(kind=nxi1), dimension(:), intent(out) data, integer, dimension(:), intent(in) data_start, integer, dimension(:), intent(in) data_size)
Definition at line 492 of file NXmodule.f90.
References nxerror(), nxgetinfo(), and nxreverse().
integer function nxmodule::nxgeti2 (type(nxhandle), intent(in) file_id, integer(kind=nxi2), dimension(:), intent(out) data)
Definition at line 313 of file NXmodule.f90.
References nxerror(), and nxgetinfo().
integer function nxmodule::nxgeti2attr (type(nxhandle), intent(in) file_id, character(len=*), intent(in) attr_name, integer(kind=nxi2), intent(out) value, integer, intent(inout), optional attr_length, integer, intent(in), optional attr_type)
Definition at line 727 of file NXmodule.f90.
References nxcstring().
integer function nxmodule::nxgeti2slab (type(nxhandle), intent(in) file_id, integer(kind=nxi2), dimension(:), intent(out) data, integer, dimension(:), intent(in) data_start, integer, dimension(:), intent(in) data_size)
Definition at line 543 of file NXmodule.f90.
References nxerror(), nxgetinfo(), and nxreverse().
integer function nxmodule::nxgeti4 (type(nxhandle), intent(in) file_id, integer(kind=nxi4), dimension(:), intent(out) data)
Definition at line 355 of file NXmodule.f90.
References nxerror(), and nxgetinfo().
integer function nxmodule::nxgeti4attr (type(nxhandle), intent(in) file_id, character(len=*), intent(in) attr_name, integer(kind=nxi4), intent(out) value, integer, intent(inout), optional attr_length, integer, intent(in), optional attr_type)
Definition at line 745 of file NXmodule.f90.
References nxcstring().
integer function nxmodule::nxgeti4slab (type(nxhandle), intent(in) file_id, integer(kind=nxi4), dimension(:), intent(out) data, integer, dimension(:), intent(in) data_start, integer, dimension(:), intent(in) data_size)
Definition at line 589 of file NXmodule.f90.
References nxerror(), nxgetinfo(), and nxreverse().
integer function, public nxmodule::nxgetinfo (type(nxhandle), intent(in) file_id, integer, intent(out) data_rank, integer, dimension(:), intent(out) data_dimensions, integer, intent(out) data_type)
Definition at line 1077 of file NXmodule.f90.
References nxreverse().
Referenced by nxgetchar(), nxgeti1(), nxgeti1slab(), nxgeti2(), nxgeti2slab(), nxgeti4(), nxgeti4slab(), nxgetr4(), nxgetr4slab(), nxgetr8(), nxgetr8slab(), nxputi1slab(), nxputi2slab(), nxputi4slab(), nxputr4slab(), nxputr8slab(), nxumodule::nxufindaxis(), nxumodule::nxufindsignal(), and nxumodule::nxuresumelink().
integer function, public nxmodule::nxgetnextattr (type(nxhandle), intent(in) file_id, character(len=*), intent(out) attr_name, integer, intent(out) attr_length, integer, intent(out) attr_type)
Definition at line 1109 of file NXmodule.f90.
References nxfstring().
Referenced by nxattrdir().
integer function, public nxmodule::nxgetnextentry (type(nxhandle), intent(in) file_id, character(len=*), intent(out) name, character(len=*), intent(out) class, integer, intent(out) data_type)
Definition at line 1093 of file NXmodule.f90.
References nxfstring().
Referenced by nxgroupdir(), nxumodule::nxufindaxis(), and nxumodule::nxufindsignal().
integer function nxmodule::nxgetr4 (type(nxhandle), intent(in) file_id, real(kind=nxr4), dimension(:), intent(out) data)
Definition at line 392 of file NXmodule.f90.
References nxerror(), and nxgetinfo().
integer function nxmodule::nxgetr4attr (type(nxhandle), intent(in) file_id, character(len=*), intent(in) attr_name, real(kind=nxr4), intent(out) value, integer, intent(inout), optional attr_length, integer, intent(in), optional attr_type)
Definition at line 763 of file NXmodule.f90.
References nxcstring().
integer function nxmodule::nxgetr4slab (type(nxhandle), intent(in) file_id, real(kind=nxr4), dimension(:), intent(out) data, integer, dimension(:), intent(in) data_start, integer, dimension(:), intent(in) data_size)
Definition at line 630 of file NXmodule.f90.
References nxerror(), nxgetinfo(), and nxreverse().
integer function nxmodule::nxgetr8 (type(nxhandle), intent(in) file_id, real(kind=nxr8), dimension(:), intent(out) data)
Definition at line 424 of file NXmodule.f90.
References nxerror(), and nxgetinfo().
integer function nxmodule::nxgetr8attr (type(nxhandle), intent(in) file_id, character(len=*), intent(in) attr_name, real(kind=nxr8), intent(out) value, integer, intent(inout), optional attr_length, integer, intent(in), optional attr_type)
Definition at line 781 of file NXmodule.f90.
References nxcstring().
integer function nxmodule::nxgetr8slab (type(nxhandle), intent(in) file_id, real(kind=nxr8), dimension(:), intent(out) data, integer, dimension(:), intent(in) data_start, integer, dimension(:), intent(in) data_size)
Definition at line 670 of file NXmodule.f90.
References nxerror(), nxgetinfo(), and nxreverse().
integer function, public nxmodule::nxgroupdir (type(nxhandle), intent(inout) file_id, integer, intent(out) item_number, character(len=*), dimension(:) item_name, character(len=*), dimension(:) item_class)
Definition at line 1212 of file NXmodule.f90.
References nxerror(), nxgetnextentry(), and nxinitgroupdir().
Referenced by nxumodule::nxufindclass(), nxumodule::nxufinddata(), nxumodule::nxufindgroup(), and nxumodule::nxuresumelink().
integer function, public nxmodule::nxinitattrdir (type(nxhandle), intent(inout) file_id)
Definition at line 1260 of file NXmodule.f90.
Referenced by nxattrdir().
integer function, public nxmodule::nxinitgroupdir (type(nxhandle), intent(inout) file_id)
Definition at line 1201 of file NXmodule.f90.
Referenced by nxgroupdir(), nxumodule::nxufindaxis(), and nxumodule::nxufindsignal().
integer function, public nxmodule::nxmakedata (type(nxhandle), intent(in) file_id, character(len=*), intent(in) data_name, integer, intent(in) data_type, integer, intent(in) data_rank, integer, dimension(:), intent(in) data_dimensions, integer, intent(in), optional compress_type, integer, dimension(:), intent(in), optional chunk_size)
Definition at line 196 of file NXmodule.f90.
References nxcstring().
Referenced by nxumodule::nxuresumelink().
integer function, public nxmodule::nxmakegroup (type(nxhandle), intent(in) file_id, character(len=*), intent(in) group_name, character(len=*), intent(in) group_class)
Definition at line 159 of file NXmodule.f90.
References nxcstring().
Referenced by nxumodule::nxuwritegroup().
integer function, public nxmodule::nxmakelink (type(nxhandle), intent(in) file_id, type(nxlink), intent(in) link)
Definition at line 1171 of file NXmodule.f90.
integer function, public nxmodule::nxopen (character(len=*), intent(in) file_name, integer, intent(in) access_method, type(nxhandle), intent(out) file_id)
Definition at line 122 of file NXmodule.f90.
References nxcstring().
integer function, public nxmodule::nxopendata (type(nxhandle), intent(in) file_id, character(len=*), intent(in) data_name)
Definition at line 227 of file NXmodule.f90.
References nxcstring().
Referenced by nxumodule::nxufindaxis(), nxumodule::nxufindsignal(), and nxumodule::nxuresumelink().
integer function, public nxmodule::nxopengroup (type(nxhandle), intent(in) file_id, character(len=*), intent(in) group_name, character(len=*), intent(in) group_class)
Definition at line 172 of file NXmodule.f90.
References nxcstring().
Referenced by nxumodule::nxuresumelink(), and nxumodule::nxuwritegroup().
integer function nxmodule::nxputchar (type(nxhandle), intent(in) file_id, character(len=*), intent(in) data)
Definition at line 884 of file NXmodule.f90.
References nxcstring().
integer function nxmodule::nxputcharattr (type(nxhandle), intent(in) file_id, character(len=*), intent(in) name, character(len=*), intent(in) value, integer, intent(in), optional value_length, integer, intent(in), optional value_type)
Definition at line 1059 of file NXmodule.f90.
References nxcstring().
integer function nxmodule::nxputi1 (type(nxhandle), intent(in) file_id, integer(kind=nxi1), dimension(:), intent(in) data)
Definition at line 824 of file NXmodule.f90.
integer function nxmodule::nxputi1attr (type(nxhandle), intent(in) file_id, character(len=*), intent(in) name, integer(kind=nxi1), intent(in) value, integer, intent(in), optional value_length, integer, intent(in), optional value_type)
Definition at line 979 of file NXmodule.f90.
References nxcstring().
integer function nxmodule::nxputi1slab (type(nxhandle), intent(in) file_id, integer(kind=nxi1), dimension(:), intent(in) data, integer, dimension(:), intent(in) data_start, integer, dimension(:), intent(in) data_size)
Definition at line 900 of file NXmodule.f90.
References nxgetinfo(), and nxreverse().
integer function nxmodule::nxputi2 (type(nxhandle), intent(in) file_id, integer(kind=nxi2), dimension(:), intent(in) data)
Definition at line 836 of file NXmodule.f90.
integer function nxmodule::nxputi2attr (type(nxhandle), intent(in) file_id, character(len=*), intent(in) name, integer(kind=nxi2), intent(in) value, integer, intent(in), optional value_length, integer, intent(in), optional value_type)
Definition at line 995 of file NXmodule.f90.
References nxcstring().
integer function nxmodule::nxputi2slab (type(nxhandle), intent(in) file_id, integer(kind=nxi2), dimension(:), intent(in) data, integer, dimension(:), intent(in) data_start, integer, dimension(:), intent(in) data_size)
Definition at line 915 of file NXmodule.f90.
References nxgetinfo(), and nxreverse().
integer function nxmodule::nxputi4 (type(nxhandle), intent(in) file_id, integer(kind=nxi4), dimension(:), intent(in) data)
Definition at line 848 of file NXmodule.f90.
integer function nxmodule::nxputi4attr (type(nxhandle), intent(in) file_id, character(len=*), intent(in) name, integer(kind=nxi4), intent(in) value, integer, intent(in), optional value_length, integer, intent(in), optional value_type)
Definition at line 1011 of file NXmodule.f90.
References nxcstring().
integer function nxmodule::nxputi4slab (type(nxhandle), intent(in) file_id, integer(kind=nxi4), dimension(:), intent(in) data, integer, dimension(:), intent(in) data_start, integer, dimension(:), intent(in) data_size)
Definition at line 930 of file NXmodule.f90.
References nxgetinfo(), and nxreverse().
integer function nxmodule::nxputr4 (type(nxhandle), intent(in) file_id, real(kind=nxr4), dimension(:), intent(in) data)
Definition at line 860 of file NXmodule.f90.
integer function nxmodule::nxputr4attr (type(nxhandle), intent(in) file_id, character(len=*), intent(in) name, real(kind=nxr4), intent(in) value, integer, intent(in), optional value_length, integer, intent(in), optional value_type)
Definition at line 1027 of file NXmodule.f90.
References nxcstring().
integer function nxmodule::nxputr4slab (type(nxhandle), intent(in) file_id, real(kind=nxr4), dimension(:), intent(in) data, integer, dimension(:), intent(in) data_start, integer, dimension(:), intent(in) data_size)
Definition at line 945 of file NXmodule.f90.
References nxgetinfo(), and nxreverse().
integer function nxmodule::nxputr8 (type(nxhandle), intent(in) file_id, real(kind=nxr8), dimension(:), intent(in) data)
Definition at line 872 of file NXmodule.f90.
integer function nxmodule::nxputr8attr (type(nxhandle), intent(in) file_id, character(len=*), intent(in) name, real(kind=nxr8), intent(in) value, integer, intent(in), optional value_length, integer, intent(in), optional value_type)
Definition at line 1043 of file NXmodule.f90.
References nxcstring().
integer function nxmodule::nxputr8slab (type(nxhandle), intent(in) file_id, real(kind=nxr8), dimension(:), intent(in) data, integer, dimension(:), intent(in) data_start, integer, dimension(:), intent(in) data_size)
Definition at line 960 of file NXmodule.f90.
References nxgetinfo(), and nxreverse().
integer function, dimension(size(dimensions)), public nxmodule::nxreverse (integer, intent(in) rank, integer, dimension(:), intent(in) dimensions)
Definition at line 1303 of file NXmodule.f90.
Referenced by nxgeti1slab(), nxgeti2slab(), nxgeti4slab(), nxgetinfo(), nxgetr4slab(), nxgetr8slab(), nxputi1slab(), nxputi2slab(), nxputi4slab(), nxputr4slab(), and nxputr8slab().
logical function, public nxmodule::nxsameid (type(nxhandle), intent(in) file_id, type(nxlink), intent(in) first_id, type(nxlink), intent(in) second_id)
Definition at line 1153 of file NXmodule.f90.
Referenced by nxumodule::nxuresumelink().
Member Data Documentation
character(len=*), parameter, public nxmodule::nexus_version = "2.0.1"
Definition at line 33 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_char = 4
Definition at line 45 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_comp_huf = 400
Definition at line 58 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_comp_lzw = 200
Definition at line 56 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_comp_none = 100
Definition at line 55 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_comp_rle = 300
Definition at line 57 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_eod = -1
Definition at line 43 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_error = 0
Definition at line 42 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_float32 = 5
Definition at line 46 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_float64 = 6
Definition at line 47 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_int16 = 22
Definition at line 50 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_int32 = 24
Definition at line 52 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_int8 = 20
Definition at line 48 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_maxnamelen = 64
Definition at line 63 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_maxrank = 32
Definition at line 62 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_maxstack = 20
Definition at line 64 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_ok = 1
Definition at line 41 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_uint16 = 23
Definition at line 51 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_uint32 = 25
Definition at line 53 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_uint8 = 21
Definition at line 49 of file NXmodule.f90.
integer, parameter, public nxmodule::nx_unlimited = -1
Definition at line 60 of file NXmodule.f90.
integer, parameter, public nxmodule::nxacc_create = 3
Definition at line 37 of file NXmodule.f90.
integer, parameter, public nxmodule::nxacc_create4 = 4
Definition at line 38 of file NXmodule.f90.
integer, parameter, public nxmodule::nxacc_create5 = 5
Definition at line 39 of file NXmodule.f90.
integer, parameter, public nxmodule::nxacc_rdwr = 2
Definition at line 36 of file NXmodule.f90.
integer, parameter, public nxmodule::nxacc_read = 1
Definition at line 35 of file NXmodule.f90.
integer, parameter, public nxmodule::nxi1 = selected_int_kind(2)
Definition at line 66 of file NXmodule.f90.
integer, parameter, public nxmodule::nxi2 = selected_int_kind(4)
Definition at line 67 of file NXmodule.f90.
integer, parameter, public nxmodule::nxi4 = selected_int_kind(8)
Definition at line 68 of file NXmodule.f90.
integer, parameter, public nxmodule::nxr4 = kind(1.0)
Definition at line 69 of file NXmodule.f90.
integer, parameter, public nxmodule::nxr8 = kind(1.0D0)
Definition at line 70 of file NXmodule.f90.
The documentation for this module was generated from the following file:
bindings/f90/NXmodule.f90