NXvalidate: org.nexusformat.nxvalidate.NXReducedToTree Class Reference
org.nexusformat.nxvalidate.NXReducedToTree Class Reference
This maps the NX Reduced XML Document (as a DOM document) to a JTree model.
Public Member Functions
NXReducedToTree (TreeNode root)
void updateTree ()
Object getRoot ()
boolean isLeaf (Object aNode)
int getChildCount (Object parent)
Object getChild (Object parent, int index)
int getIndexOfChild (Object parent, Object child)
void valueForPathChanged (TreePath path, Object newValue)
void addTreeModelListener (TreeModelListener listener)
void removeTreeModelListener (TreeModelListener listener)
void fireTreeNodesChanged (TreeModelEvent e)
void fireTreeNodesInserted (TreeModelEvent e)
void fireTreeNodesRemoved (TreeModelEvent e)
void fireTreeStructureChanged (TreeModelEvent e)
Detailed Description
This maps the NX Reduced XML Document (as a DOM document) to a JTree model.
Author:
Stephen Rankin
Definition at line 45 of file NXReducedToTree.java.
Constructor & Destructor Documentation
org.nexusformat.nxvalidate.NXReducedToTree.NXReducedToTree (TreeNode root)
Definition at line 50 of file NXReducedToTree.java.
Member Function Documentation
void org.nexusformat.nxvalidate.NXReducedToTree.addTreeModelListener (TreeModelListener listener)
Definition at line 111 of file NXReducedToTree.java.
void org.nexusformat.nxvalidate.NXReducedToTree.fireTreeNodesChanged (TreeModelEvent e)
Definition at line 128 of file NXReducedToTree.java.
void org.nexusformat.nxvalidate.NXReducedToTree.fireTreeNodesInserted (TreeModelEvent e)
Definition at line 141 of file NXReducedToTree.java.
void org.nexusformat.nxvalidate.NXReducedToTree.fireTreeNodesRemoved (TreeModelEvent e)
Definition at line 154 of file NXReducedToTree.java.
void org.nexusformat.nxvalidate.NXReducedToTree.fireTreeStructureChanged (TreeModelEvent e)
Definition at line 167 of file NXReducedToTree.java.
Referenced by org.nexusformat.nxvalidate.NXReducedToTree.updateTree().
Object org.nexusformat.nxvalidate.NXReducedToTree.getChild (Object parent, int index)
Definition at line 91 of file NXReducedToTree.java.
References org.nexusformat.nxvalidate.NXNodeMapper.getChildAt().
int org.nexusformat.nxvalidate.NXReducedToTree.getChildCount (Object parent)
Definition at line 83 of file NXReducedToTree.java.
References org.nexusformat.nxvalidate.NXNodeMapper.getChildCount().
int org.nexusformat.nxvalidate.NXReducedToTree.getIndexOfChild (Object parent, Object child)
Definition at line 99 of file NXReducedToTree.java.
References org.nexusformat.nxvalidate.NXNodeMapper.getIndex().
Object org.nexusformat.nxvalidate.NXReducedToTree.getRoot ()
Definition at line 63 of file NXReducedToTree.java.
boolean org.nexusformat.nxvalidate.NXReducedToTree.isLeaf (Object aNode)
Definition at line 70 of file NXReducedToTree.java.
References org.nexusformat.nxvalidate.NXNodeMapper.getChildCount().
void org.nexusformat.nxvalidate.NXReducedToTree.removeTreeModelListener (TreeModelListener listener)
Definition at line 120 of file NXReducedToTree.java.
void org.nexusformat.nxvalidate.NXReducedToTree.updateTree ()
Definition at line 55 of file NXReducedToTree.java.
References org.nexusformat.nxvalidate.NXReducedToTree.fireTreeStructureChanged().
Referenced by org.nexusformat.nxvalidate.FileActions.bulkLoad(), org.nexusformat.nxvalidate.FileActions.bulkValidate(), and org.nexusformat.nxvalidate.FileActions.run().
void org.nexusformat.nxvalidate.NXReducedToTree.valueForPathChanged (TreePath path, Object newValue)
Definition at line 107 of file NXReducedToTree.java.
The documentation for this class was generated from the following file:
applications/NXvalidate/src/org/nexusformat/nxvalidate/NXReducedToTree.java