NXvalidate: org.nexusformat.nxvalidate.SVRLNodeFilter Class Reference
org.nexusformat.nxvalidate.SVRLNodeFilter Class Reference
Implementation of NodeFilterInterface which filters out elements in a NEXUS reduced file if they have failed the validation tests.
Public Member Functions
SVRLNodeFilter ()
void setFilterDocument (Document filterDoc)
Sets a DOM document (filter document) that contains a list of nodes that have failed any validation tests, for example, the SVRL file.
void setDocument (Document doc)
Sets the document to which to apply the filter.
ArrayList< Node > getBadNodeList ()
A list of nodes which are bad.
ArrayList< Node > getWarnNodeList ()
A list of nodes which have a warning.
void resetNodes ()
Reset the nodes to indicate that they are now good nodes, i.e.
Detailed Description
Implementation of NodeFilterInterface which filters out elements in a NEXUS reduced file if they have failed the validation tests.
Author:
Stephen Rankin
Definition at line 48 of file SVRLNodeFilter.java.
Constructor & Destructor Documentation
org.nexusformat.nxvalidate.SVRLNodeFilter.SVRLNodeFilter ()
Definition at line 56 of file SVRLNodeFilter.java.
Member Function Documentation
ArrayList<Node> org.nexusformat.nxvalidate.SVRLNodeFilter.getBadNodeList ()
A list of nodes which are bad.
Returns:
the list of bad nodes
Implements org.nexusformat.nxvalidate.NodeFilterInterface.
Definition at line 88 of file SVRLNodeFilter.java.
Referenced by org.nexusformat.nxvalidate.FileActions.validateFile().
ArrayList<Node> org.nexusformat.nxvalidate.SVRLNodeFilter.getWarnNodeList ()
A list of nodes which have a warning.
Returns:
Implements org.nexusformat.nxvalidate.NodeFilterInterface.
Definition at line 107 of file SVRLNodeFilter.java.
void org.nexusformat.nxvalidate.SVRLNodeFilter.resetNodes ()
Reset the nodes to indicate that they are now good nodes, i.e.
resets them back to a pre-validated state.
Implements org.nexusformat.nxvalidate.NodeFilterInterface.
Definition at line 126 of file SVRLNodeFilter.java.
Referenced by org.nexusformat.nxvalidate.FileActions.validateFile().
void org.nexusformat.nxvalidate.SVRLNodeFilter.setDocument (Document doc)
Sets the document to which to apply the filter.
The document in this case is the reduced NeXus file.
Parameters:
doc a DOM document.
Implements org.nexusformat.nxvalidate.NodeFilterInterface.
Definition at line 78 of file SVRLNodeFilter.java.
Referenced by org.nexusformat.nxvalidate.FileActions.validateFile().
void org.nexusformat.nxvalidate.SVRLNodeFilter.setFilterDocument (Document filterDoc)
Sets a DOM document (filter document) that contains a list of nodes that have failed any validation tests, for example, the SVRL file.
Parameters:
filterDoc a DOM document.
Implements org.nexusformat.nxvalidate.NodeFilterInterface.
Definition at line 67 of file SVRLNodeFilter.java.
Referenced by org.nexusformat.nxvalidate.FileActions.validateFile().
The documentation for this class was generated from the following file:
applications/NXvalidate/src/org/nexusformat/nxvalidate/SVRLNodeFilter.java