NeXus: IOstream like interface
IOstream like interface
Classes
class NeXus::Stream::Attr
Serialisable attribute.
class NeXus::Stream::Group
Serialisable NeXus group object.
class NeXus::Stream::Data
Serialisable data object that contains attributes.
Enumerations
enum NeXus::Stream::StreamModifier { NeXus::Stream::Close = 0 }
Functions
File & NeXus::Stream::operator<< (File &nf, const ISerialisable &obj)
File & NeXus::Stream::operator>> (File &nf, const ISerialisable &obj)
File & NeXus::Stream::operator<< (File &nf, const StreamModifier sm)
File & NeXus::Stream::operator>> (File &nf, const StreamModifier sm)
Detailed Description
Enumeration Type Documentation
enum NeXus::Stream::StreamModifier
Enumerator:
Close
Definition at line 65 of file NeXusStream.hpp.
Function Documentation
File & NeXus::Stream::operator<< (File & nf, const ISerialisable & obj)
Definition at line 226 of file NeXusStream.cpp.
References NeXus::Stream::ISerialisable::writeToFile().
File & NeXus::Stream::operator<< (File & nf, const StreamModifier sm)
Definition at line 238 of file NeXusStream.cpp.
References NeXus::Stream::Close, NeXus::File::closeData(), NeXus::File::closeGroup(), and NeXus::File::isDataSetOpen().
File & NeXus::Stream::operator>> (File & nf, const ISerialisable & obj)
Definition at line 232 of file NeXusStream.cpp.
References NeXus::Stream::ISerialisable::readFromFile().
File & NeXus::Stream::operator>> (File & nf, const StreamModifier sm)
Definition at line 259 of file NeXusStream.cpp.
References NeXus::Stream::Close, NeXus::File::closeData(), NeXus::File::closeGroup(), and NeXus::File::isDataSetOpen().