NeXus: nxs.tree.NXattr Class Reference
nxs.tree.NXattr Class Reference
Class for NeXus attributes of a NXfield or NXgroup object.
Public Member Functions
def __init__
def __str__
def __repr__
def __eq__
Return true if the value of the attribute is the same as the other.
Properties
nxdata = property(_getdata,doc="The attribute values")
dtype = property(_getdtype, "Data type of NeXus attribute")
Detailed Description
Class for NeXus attributes of a NXfield or NXgroup object.
This class is only used for NeXus attributes that are stored in a NeXus file and helps to distinguish them from Python attributes. There are two Python attributes for each NeXus attribute.
Python Attributes
nxdata : string, Numpy scalar, or Numpy ndarray The value of the NeXus attribute. dtype : string The data type of the NeXus attribute. This is set to 'char' for a string attribute or the string of the corresponding Numpy data type for a numeric attribute.
NeXus Attributes
NeXus attributes are stored in the 'attrs' dictionary of the parent object, NXfield or NXgroup, but can often be referenced or assigned using the attribute name as if it were an object attribute.
For example, after assigning the NXfield, the following three attribute assignments are all equivalent::
>>> entry.sample.temperature = NXfield(40.0)
>>> entry.sample.temperature.attrs['units'] = 'K'
>>> entry.sample.temperature.units = NXattr('K')
>>> entry.sample.temperature.units = 'K'
The third version above is only allowed for NXfield attributes and is not allowed if the attribute has the same name as one of the following internally defined attributes, i.e.,
['entries', 'attrs', 'dtype','shape']
or if the attribute name begins with 'nx' or '_'. It is only possible to reference attributes with one of the proscribed names using the 'attrs' dictionary.
Definition at line 615 of file tree.py.
Constructor & Destructor Documentation
def nxs.tree.NXattr.__init__ (self, value = None, dtype = '')
Definition at line 618 of file tree.py.
References nxs.tree.NXattr._data, and nxs.tree.NXattr._dtype.
Member Function Documentation
def nxs.tree.NXattr.__eq__ (self, other)
Return true if the value of the attribute is the same as the other.
Definition at line 655 of file tree.py.
References nxs.tree.NXattr._data, nxs.tree.NXattr._dtype, and nxs.tree.NXattr.nxdata.
def nxs.tree.NXattr.__repr__ (self)
Definition at line 645 of file tree.py.
References nxs.tree.NXattr.dtype, and nxs.tree.NXattr.nxdata.
def nxs.tree.NXattr.__str__ (self)
Definition at line 642 of file tree.py.
References nxs.tree.NXattr.nxdata.
Property Documentation
nxs.tree.NXattr.dtype = property(_getdtype, "Data type of NeXus attribute") static
Definition at line 672 of file tree.py.
Referenced by nxs.tree.NXfield.__deepcopy__(), nxs.tree.NXattr.__repr__(), nxs.tree.NXfield.__repr__(), nxs.tree.NXfield.__str__(), nxs.tree.NXfield.add(), nxs.tree.NXfield.put(), nxs.tree.NXfield.walk(), and nxs.tree.NXfield.write().
nxs.tree.NXattr.nxdata = property(_getdata,doc="The attribute values") static
Definition at line 671 of file tree.py.
Referenced by nxs.tree.NXfield.__add__(), nxs.tree.NXfield.__array__(), nxs.tree.NXfield.__div__(), nxs.tree.NXattr.__eq__(), nxs.tree.NXfield.__eq__(), nxs.tree.NXfield.__mul__(), nxs.tree.NXfield.__ne__(), nxs.tree.NXfield.__pow__(), nxs.tree.NXfield.__rdiv__(), nxs.tree.NXattr.__repr__(), nxs.tree.NXfield.__setitem__(), nxs.tree.NXattr.__str__(), nxs.tree.NXfield.__sub__(), nxs.tree.NXfield.centers(), nxs.tree.NXfield.index(), and nxs.tree.NXfield.write().
The documentation for this class was generated from the following file:
bindings/python/nxs/tree.py