NeXus: nxs.tree Namespace Reference
nxs.tree Namespace Reference
Classes
class NeXusTree
Structure-based interface to the NeXus file API.
class AttrDict
A dictionary class to assign all attributes to the NXattr class.
class NXattr
Class for NeXus attributes of a NXfield or NXgroup object.
class NXobject
Abstract base class for elements in NeXus files.
class NXfield
A NeXus data field.
class PylabPlotter
Matplotlib plotter class for NeXus data.
class NXgroup
A NeXus group object.
class NXlink
Class for NeXus linked objects.
class NXlinkfield
Class for a NeXus linked field.
class NXlinkgroup
Class for a NeXus linked group.
class NXentry
NXentry group.
class NXsubentry
NXsubentry group.
class NXdata
NXdata group.
class NXmonitor
NXmonitor group.
class NXlog
NXlog group.
Functions
def centers
Return the centers of the axes.
def setmemory
Set the memory limit for data arrays (in MB).
def label
Return a label for a data field suitable for use on a graph axis.
def load
Read a NeXus file returning a tree of objects.
def save
Write a NeXus file from a tree of objects.
def tree
Read and summarize the named NeXus file.
def demo
Process a list of command line commands.
Variables
int NX_MEMORY = 500
list __all__
list _nxclasses
tuple _npattrs = filter(lambda x: not x.startswith('_'), np.ndarray.__dict__.keys())
SDS = NXfield
NXlinkdata = NXlinkfield
string docstring
nxload = load
Function Documentation
def nxs.tree.centers (signal, axes)
Return the centers of the axes.
This works regardless if the axes contain bin boundaries or centers.
Definition at line 3255 of file tree.py.
Referenced by nxs.tree.NXgroup.moment(), and nxs.tree.PylabPlotter.plot().
def nxs.tree.demo (argv)
Process a list of command line commands.
'argv' should contain program name, command, arguments, where command is one of the following: copy fromfile.nxs tofile.nxs ls f1.nxs f2.nxs ...
Definition at line 3333 of file tree.py.
References nxs.tree.load(), and nxs.tree.save().
def nxs.tree.label (field)
Return a label for a data field suitable for use on a graph axis.
Definition at line 3276 of file tree.py.
Referenced by nxs.tree.PylabPlotter.plot().
def nxs.tree.load (filename, mode = 'r')
Read a NeXus file returning a tree of objects.
This is aliased to 'read' because of potential name clashes with Numpy
Definition at line 3291 of file tree.py.
Referenced by nxs.tree.demo(), and nxs.tree.tree().
def nxs.tree.save (filename, group, format = 'w5')
Write a NeXus file from a tree of objects.
Definition at line 3305 of file tree.py.
Referenced by nxs.tree.demo().
def nxs.tree.setmemory (value)
Set the memory limit for data arrays (in MB).
Definition at line 3268 of file tree.py.
def nxs.tree.tree (file)
Read and summarize the named NeXus file.
Definition at line 3320 of file tree.py.
References nxs.tree.load().
Variable Documentation
list nxs.tree.__all__
Initial value:
 ['NeXusTree', 'NXobject', 'NXfield', 'NXgroup', 'NXattr',
            'NX_MEMORY', 'setmemory', 'load', 'save', 'tree', 'centers',
            'NXlink', 'NXlinkfield', 'NXlinkgroup', 'SDS', 'NXlinkdata']
Definition at line 250 of file tree.py.
tuple nxs.tree._npattrs = filter(lambda x: not x.startswith('_'), np.ndarray.__dict__.keys())
Definition at line 674 of file tree.py.
list nxs.tree._nxclasses
Initial value:
 ['NXroot', 'NXentry', 'NXsubentry', 'NXdata', 'NXmonitor',
               'NXlog', 'NXsample', 'NXinstrument', 'NXaperture', 'NXattenuator',
               'NXbeam', 'NXbeam_stop', 'NXbending_magnet', 'NXcharacterization',
               'NXcollection', 'NXcollimator', 'NXcrystal', 'NXdetector',
               'NXdisk_chopper', 'NXenvironment', 'NXevent_data',
               'NXfermi_chopper', 'NXfilter', 'NXflipper', 'NXgeometry',
               'NXguide', 'NXinsertion_device', 'NXmirror', 'NXmoderator',
               'NXmonochromator', 'NXnote', 'NXorientation', 'NXparameter',
               'NXpolarizer', 'NXpositioner', 'NXprocess', 'NXsensor', 'NXshape',
               'NXsource', 'NXtranslation', 'NXuser', 'NXvelocity_selector', 'NXtree']
Definition at line 255 of file tree.py.
string nxs.tree.docstring
Initial value:
 """
                     %s group. This is a subclass of the NXgroup class.
                     See the NXgroup documentation for more details.
                     """
Definition at line 3237 of file tree.py.
int nxs.tree.NX_MEMORY = 500
Definition at line 248 of file tree.py.
nxs.tree.NXlinkdata = NXlinkfield
Definition at line 2805 of file tree.py.
nxs.tree.nxload = load
Definition at line 3298 of file tree.py.
nxs.tree.SDS = NXfield
Definition at line 1785 of file tree.py.