#ifndef QCEPCALIBRANTDSPACINGSMODELPTR_H
#define QCEPCALIBRANTDSPACINGSMODELPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QcepCalibrantDSpacingsModel)

#endif // QCEPCALIBRANTDSPACINGSMODELPTR_H

