#ifndef QCEPIMAGEPLOTWIDGETSETTINGSPTR_H
#define QCEPIMAGEPLOTWIDGETSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QcepImagePlotWidgetSettings)

#endif // QCEPIMAGEPLOTWIDGETSETTINGSPTR_H
