#ifndef QCEPFILEBROWSERMODELUPDATER_PTR_H
#define QCEPFILEBROWSERMODELUPDATER_PTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QcepFileBrowserModelUpdater)

#endif // QCEPFILEBROWSERMODELUPDATER_PTR_H
