#ifndef QCEPFILEBROWSERMODELUPDATERTHREAD_PTR_H
#define QCEPFILEBROWSERMODELUPDATERTHREAD_PTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QcepFileBrowserModelUpdaterThread)

#endif // QCEPFILEBROWSERMODELUPDATERTHREAD_PTR_H
