#ifndef QXRDTESTIMAGEGENERATORTHREADPTR_H
#define QXRDTESTIMAGEGENERATORTHREADPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdTestImageGeneratorThread)

#endif // QXRDTESTIMAGEGENERATORTHREADPTR_H
