#ifndef QXRDSYNCHRONIZEDDETECTORCHANNELPTR_H
#define QXRDSYNCHRONIZEDDETECTORCHANNELPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdSynchronizedDetectorChannel)

#endif // QXRDSYNCHRONIZEDDETECTORCHANNELPTR_H
