#ifndef QXRDANALYSISWINDOWSETTINGSPTR_H
#define QXRDANALYSISWINDOWSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdAnalysisWindowSettings)

#endif // QXRDANALYSISWINDOWSETTINGSPTR_H
