#ifndef QXRDACQUISITIONPARAMETERPACKPTR_H
#define QXRDACQUISITIONPARAMETERPACKPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdAcquisitionParameterPack)

#endif // QXRDACQUISITIONPARAMETERPACKPTR_H

