#ifndef QXRDEXTRAIOOUTPUTSDELEGATEPTR_H
#define QXRDEXTRAIOOUTPUTSDELEGATEPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdExtraIOOutputsDelegate)

#endif // QXRDEXTRAIOOUTPUTSDELEGATEPTR_H
