#ifndef QXRDINTEGRATIONWINDOWSETTINGSPTR_H
#define QXRDINTEGRATIONWINDOWSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdIntegrationWindowSettings)

#endif // QXRDINTEGRATIONWINDOWSETTINGSPTR_H
