#ifndef QXRDACQUISITIONEXTRAINPUTSCHANNEL_PTR_H
#define QXRDACQUISITIONEXTRAINPUTSCHANNEL_PTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdAcquisitionExtraInputsChannel)

#endif // QXRDACQUISITIONEXTRAINPUTSCHANNEL_PTR_H
