#ifndef QXRDACQUISITIONWINDOWSETTINGSPTR_H
#define QXRDACQUISITIONWINDOWSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdAcquisitionWindowSettings)

#endif // QXRDACQUISITIONWINDOWSETTINGSPTR_H
