#ifndef QXRDTESTSCANPLOTDATAVISHELPERPTR_H
#define QXRDTESTSCANPLOTDATAVISHELPERPTR_H

#ifdef HAVE_DATAVIS

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdTestScanPlotDataVisHelper)

#endif

#endif // QXRDTESTSCANPLOTDATAVISHELPERPTR_H
