#ifndef QXRDCALIBRANTDSPACINGSMODELPTR_H
#define QXRDCALIBRANTDSPACINGSMODELPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdCalibrantDSpacingsModel)

#endif // QXRDCALIBRANTDSPACINGSMODELPTR_H

