#ifndef QXRDACQUISITIONEXECUTIONTHREADPTR_H
#define QXRDACQUISITIONEXECUTIONTHREADPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdAcquisitionExecutionThread)

#endif // QXRDACQUISITIONEXECUTIONTHREADPTR_H

