#ifndef QXRDDETECTORSETTINGSSIMULATEDPTR_H
#define QXRDDETECTORSETTINGSSIMULATEDPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdDetectorSettingsSimulated)

#endif // QXRDDETECTORSETTINGSSIMULATEDPTR_H
