#ifndef QXRDCALCULATORWINDOWSETTINGSPTR_H
#define QXRDCALCULATORWINDOWSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdCalculatorWindowSettings)

#endif // QXRDCALCULATORWINDOWSETTINGSPTR_H
