#ifndef QXRDACQUISITIONEVENTLOGWINDOWPTR_H
#define QXRDACQUISITIONEVENTLOGWINDOWPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdAcquisitionEventLogWindow)

#endif // QXRDACQUISITIONEVENTLOGWINDOWPTR_H
