#ifndef QXRDDETECTORPLUGININTERFACEPTR_H
#define QXRDDETECTORPLUGININTERFACEPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdDetectorPluginInterface)

#endif // QXRDDETECTORPLUGININTERFACEPTR_H
