#ifndef QXRDROICOORDINATESLISTMODELPTR_H
#define QXRDROICOORDINATESLISTMODELPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdROICoordinatesListModel)

#endif // QXRDROICOORDINATESLISTMODELPTR_H

