#ifndef QXRDSYNCHRONIZEDOUTPUTCHANNELPTR_H
#define QXRDSYNCHRONIZEDOUTPUTCHANNELPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdSynchronizedOutputChannel)

#endif // QXRDSYNCHRONIZEDOUTPUTCHANNELPTR_H
