#ifndef QXRDDETECTORSETTINGSPERKINELMERPTR_H
#define QXRDDETECTORSETTINGSPERKINELMERPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdDetectorSettingsPerkinElmer)

#endif // QXRDDETECTORSETTINGSPERKINELMERPTR_H
