#ifndef QXRDHISTOGRAMPLOTWIDGETSETTINGSPTR_H
#define QXRDHISTOGRAMPLOTWIDGETSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdHistogramPlotWidgetSettings)

#endif // QXRDHISTOGRAMPLOTWIDGETSETTINGSPTR_H
