#ifndef QXRDDETECTORSETTINGSPILATUSPTR_H
#define QXRDDETECTORSETTINGSPILATUSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdDetectorSettingsPilatus)

#endif // QXRDDETECTORSETTINGSPILATUSPTR_H
