#ifndef QXRDDARKACQUISITIONPARAMETERPACKPTR_H
#define QXRDDARKACQUISITIONPARAMETERPACKPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdDarkAcquisitionParameterPack)

#endif // QXRDDARKACQUISITIONPARAMETERPACKPTR_H

