#ifndef QXRDDETECTORSETTINGSEPICSAREAPTR_H
#define QXRDDETECTORSETTINGSEPICSAREAPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdDetectorSettingsEpicsArea)

#endif // QXRDDETECTORSETTINGSEPICSAREAPTR_H
