#ifndef QXRDACQUISITIONSCALERMODELPTR_H
#define QXRDACQUISITIONSCALERMODELPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdAcquisitionScalerModel)

#endif // QXRDACQUISITIONSCALERMODELPTR_H

