#ifndef QXRDPROCESSOREXECUTIONTHREADPTR_H
#define QXRDPROCESSOREXECUTIONTHREADPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdProcessorExecutionThread)

#endif // QXRDPROCESSOREXECUTIONTHREADPTR_H
