#ifndef QXRDCALIBRANTWINDOWSETTINGSPTR_H
#define QXRDCALIBRANTWINDOWSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdCalibrantWindowSettings)

#endif // QXRDCALIBRANTWINDOWSETTINGSPTR_H
