#ifndef QXRDCENTERINGPLOTWIDGETSETTINGSPTR_H
#define QXRDCENTERINGPLOTWIDGETSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdCenteringPlotWidgetSettings)

#endif // QXRDCENTERINGPLOTWIDGETSETTINGSPTR_H
