#ifndef QXRDACQUISITIONSCALERDIALOGPTR_H
#define QXRDACQUISITIONSCALERDIALOGPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdAcquisitionScalerDialog)

#endif // QXRDACQUISITIONSCALERDIALOGPTR_H

