#ifndef QXRDTESTSCANGENERATORTHREADPTR_H
#define QXRDTESTSCANGENERATORTHREADPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdTestScanGeneratorThread)

#endif // QXRDTESTSCANGENERATORTHREADPTR_H
