#ifndef QXRDOUTPUTFILEFORMATTERSETTINGSPTR_H
#define QXRDOUTPUTFILEFORMATTERSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdOutputFileFormatterSettings)

#endif // QXRDOUTPUTFILEFORMATTERSETTINGSPTR_H
