#ifndef QXRDIMAGEPLOTWIDGETSETTINGSPTR_H
#define QXRDIMAGEPLOTWIDGETSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdImagePlotWidgetSettings)

#endif // QXRDIMAGEPLOTWIDGETSETTINGSPTR_H
