#ifndef QXRDACQUISITIONEXTRAINPUTSCHANNEL_PTR_H
#define QXRDACQUISITIONEXTRAINPUTSCHANNEL_PTR_H

#include <QSharedPointer>

class QxrdAcquisitionExtraInputsChannel;

typedef QSharedPointer<QxrdAcquisitionExtraInputsChannel> QxrdAcquisitionExtraInputsChannelPtr;
typedef QWeakPointer<QxrdAcquisitionExtraInputsChannel> QxrdAcquisitionExtraInputsChannelWPtr;

#endif // QXRDACQUISITIONEXTRAINPUTSCHANNEL_PTR_H
