#ifndef QXRDFILEBROWSERMODELUPDATERTHREAD_PTR_H
#define QXRDFILEBROWSERMODELUPDATERTHREAD_PTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdFileBrowserModelUpdaterThread)

#endif // QXRDFILEBROWSERMODELUPDATERTHREAD_PTR_H
