#ifndef QXRDDISTORTIONPLOTWIDGETSETTINGSPTR_H
#define QXRDDISTORTIONPLOTWIDGETSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdDistortionPlotWidgetSettings)

#endif // QXRDDISTORTIONPLOTWIDGETSETTINGSPTR_H
