#ifndef QXRDPERKINELMERPLUGININTERFACE_PTR_H
#define QXRDPERKINELMERPLUGININTERFACE_PTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdPerkinElmerPluginInterface)

#endif // QXRDPERKINELMERPLUGININTERFACE_PTR_H
