#ifndef QXRDSYNCHRONIZEDACQUISITION_PTR_H
#define QXRDSYNCHRONIZEDACQUISITION_PTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdSynchronizedAcquisition)

#endif // QXRDSYNCHRONIZEDACQUISITION_H
