#ifndef QXRDDETECTORCONTROLWINDOWSETTINGSPTR_H
#define QXRDDETECTORCONTROLWINDOWSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdDetectorControlWindowSettings)

#endif // QXRDDETECTORCONTROLWINDOWSETTINGSPTR_H
