#ifndef QXRDDETECTORPLOTWIDGETSETTINGSPTR_H
#define QXRDDETECTORPLOTWIDGETSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdDetectorPlotWidgetSettings)

#endif // QXRDDETECTORPLOTWIDGETSETTINGSPTR_H
