#ifndef QXRDDETECTORCONTROLWINDOWSETTINGSPTR_H
#define QXRDDETECTORCONTROLWINDOWSETTINGSPTR_H

#include <QSharedPointer>

class QxrdDetectorControlWindowSettings;

typedef QSharedPointer<QxrdDetectorControlWindowSettings> QxrdDetectorControlWindowSettingsPtr;
typedef QWeakPointer<QxrdDetectorControlWindowSettings>   QxrdDetectorControlWindowSettingsWPtr;

#endif // QXRDDETECTORCONTROLWINDOWSETTINGSPTR_H
