#ifndef QXRDDETECTORSETTINGSFILEWATCHERPTR_H
#define QXRDDETECTORSETTINGSFILEWATCHERPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdDetectorSettingsFileWatcher)

#endif // QXRDDETECTORSETTINGSFILEWATCHERPTR_H
