#ifndef QXRDTESTIMAGEPLOTQWTHELPERPTR_H
#define QXRDTESTIMAGEPLOTQWTHELPERPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdTestImagePlotQwtHelper)

#endif // QXRDTESTIMAGEPLOTQWTHELPERPTR_H
