#ifndef QXRDEXTRAOUTPUTSPLOTWIDGETSETTINGSPTR_H
#define QXRDEXTRAOUTPUTSPLOTWIDGETSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdExtraOutputsPlotWidgetSettings)

#endif // QXRDEXTRAOUTPUTSPLOTWIDGETSETTINGSPTR_H
