#ifndef QXRDCENTERFINDERPLOTSETTINGSPTR_H
#define QXRDCENTERFINDERPLOTSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdCenterFinderPlotSettings)

#endif // QXRDCENTERFINDERPLOTSETTINGSPTR_H
