#ifndef QXRDHISTOGRAMDIALOGSETTINGSPTR_H
#define QXRDHISTOGRAMDIALOGSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdHistogramDialogSettings)

#endif // QXRDHISTOGRAMDIALOGSETTINGSPTR_H
