#ifndef QXRDSLICEPLOTWIDGETSETTINGSPTR_H
#define QXRDSLICEPLOTWIDGETSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdSlicePlotWidgetSettings)

#endif // QXRDSLICEPLOTWIDGETSETTINGSPTR_H
