#ifndef QXRDINTEGRATEDPLOTWIDGETSETTINGSPTR_H
#define QXRDINTEGRATEDPLOTWIDGETSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdIntegratedPlotWidgetSettings)

#endif // QXRDINTEGRATEDPLOTWIDGETSETTINGSPTR_H
