#ifndef QXRDACQUISITIONEVENTLOGMODELPTR_H
#define QXRDACQUISITIONEVENTLOGMODELPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdAcquisitionEventLogModel)

#endif // QXRDACQUISITIONEVENTLOGMODELPTR_H
