#ifndef QXRDINTEGRATORPLOTSETTINGSPTR_H
#define QXRDINTEGRATORPLOTSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdIntegratorPlotSettings)

#endif // QCEPINTEGRATORPLOTSETTINGSPTR_H
