#ifndef QXRDEXTRAIODETECTORSDELEGATEPTR_H
#define QXRDEXTRAIODETECTORSDELEGATEPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdExtraIODetectorsDelegate)

#endif // QXRDEXTRAIODETECTORSDELEGATEPTR_H
