#ifndef QXRDTESTIMAGEPLOTDATAVISHELPERPTR_H
#define QXRDTESTIMAGEPLOTDATAVISHELPERPTR_H

#ifdef HAVE_DATAVIS

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdTestImagePlotDataVisHelper)

#endif // HAVE_DATAVIS

#endif // QXRDTESTIMAGEPLOTDATAVISHELPERPTR_H
