#ifndef QXRDDETECTORPROXYLISTMODELPTR_H
#define QXRDDETECTORPROXYLISTMODELPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdDetectorProxyListModel)

#endif // QXRDDETECTORPROXYLISTMODELPTR_H

