#ifndef QXRDFILEBROWSERSETTINGSPTR_H
#define QXRDFILEBROWSERSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdFileBrowserSettings)
QCEP_SHAREDPOINTER(QxrdInputFileBrowserSettings)
QCEP_SHAREDPOINTER(QxrdOutputFileBrowserSettings)

#endif // QXRDFILEBROWSERSETTINGSPTR_H
