#ifndef QXRDDETECTORSETTINGSDEXELAPTR_H
#define QXRDDETECTORSETTINGSDEXELAPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdDetectorSettingsDexela)

#endif // QXRDDETECTORSETTINGSDEXELAPTR_H
