#ifndef QXRDSCRIPTINGWINDOWSETTINGSPTR_H
#define QXRDSCRIPTINGWINDOWSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdScriptingWindowSettings)

#endif // QXRDSCRIPTINGWINDOWSETTINGSPTR_H
