#ifndef QXRDFILEBROWSERMODELUPDATER_PTR_H
#define QXRDFILEBROWSERMODELUPDATER_PTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdFileBrowserModelUpdater)

#endif // QXRDFILEBROWSERMODELUPDATER_PTR_H
