#ifndef QXRDCENTERINGWINDOWSETTINGSPTR_H
#define QXRDCENTERINGWINDOWSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdCenteringWindowSettings)

#endif // QXRDCENTERINGWINDOWSETTINGSPTR_H
