#ifndef QXRDEXTRAINPUTSPLOTWIDGETSETTINGSPTR_H
#define QXRDEXTRAINPUTSPLOTWIDGETSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdExtraInputsPlotWidgetSettings)

#endif // QXRDEXTRAINPUTSPLOTWIDGETSETTINGSPTR_H
