#ifndef QXRDSYNCHRONIZEDINPUTCHANNELPTR_H
#define QXRDSYNCHRONIZEDINPUTCHANNELPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdSynchronizedInputChannel)

#endif // QXRDSYNCHRONIZEDINPUTCHANNELPTR_H
