#ifndef QXRDACQUISITIONEXTRAINPUTSDIALOGSETTINGSPTR_H
#define QXRDACQUISITIONEXTRAINPUTSDIALOGSETTINGSPTR_H

#include <QSharedPointer>

class QxrdAcquisitionExtraInputsDialogSettings;

typedef QSharedPointer<QxrdAcquisitionExtraInputsDialogSettings> QxrdAcquisitionExtraInputsDialogSettingsPtr;
typedef QWeakPointer<QxrdAcquisitionExtraInputsDialogSettings>   QxrdAcquisitionExtraInputsDialogSettingsWPtr;

#endif // QXRDACQUISITIONEXTRAINPUTSDIALOGSETTINGSPTR_H
