#ifndef QXRDDETECTORCONTROLWINDOWPTR_H
#define QXRDDETECTORCONTROLWINDOWPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdDetectorControlWindow)

#endif // QXRDDETECTORCONTROLWINDOWPTR_H

