NeXus: nxs.tree.NeXusTree Class Reference
nxs.tree.NeXusTree Class Reference
Structure-based interface to the NeXus file API.
Public Member Functions
def readfile
Read the NeXus file structure from the file and return a tree of NXobjects.
def writefile
Write the NeXus file structure to a file.
def readpath
Return the data on a particular file path.
Public Member Functions inherited from nxs.napi.NeXus
def __init__
Open the NeXus file returning a handle.
def __del__
Be sure to close the file before deleting the last reference.
def __str__
Return a string representation of the NeXus file handle.
def open
Opens the NeXus file handle if it is not already open.
def close
Close the NeXus file associated with handle.
def flush
Flush all data to the NeXus file.
def setnumberformat
Set the output format for the numbers of the given type (only applies to XML).
def makegroup
Create the group nxclass:name.
def openpath
Open a particular group '/path/to/group'.
def opengrouppath
Open a particular group '/path/to/group', or the dataset containing the group if the path refers to a dataset.
def opengroup
Open the group nxclass:name.
def closegroup
Close the currently open group.
def getgroupinfo
Query the currently open group returning the tuple numentries, name, nxclass.
def initgroupdir
Reset getnextentry to return the first entry in the group.
def getnextentry
Return the next entry in the group as name,nxclass tuple.
def getentries
Return a dictionary of the groups[name]=type below the existing open one.
def entries
Iterator of entries.
def getrawinfo
Returns the tuple dimensions,type for the currently open dataset.
def getinfo
Returns the tuple dimensions,type for the currently open dataset.
def opendata
Open the named data set within the current group.
def closedata
Close the currently open data set.
def makedata
Create a data element of the given type and shape.
def compmakedata
Create a data element of the given dimensions and type.
def getdata
Return the data.
def getslab
Get a slab from the data array.
def putdata
Write data into the currently open data block.
def putslab
Put a slab into the data array.
def initattrdir
Reset the getnextattr list to the first attribute.
def getattrinfo
Returns the number of attributes for the currently open group/data object.
def getnextattr
Returns the name, length, and data type for the next attribute.
def getattr
Returns the value of the named attribute.
def putattr
Saves the named attribute.
def getattrs
Returns a dicitonary of the attributes on the current node.
def attrs
Iterate over attributes.
def getgroupID
Return the id of the current group so we can link to it later.
def getdataID
Return the id of the current data so we can link to it later.
def makelink
Link the previously captured group/data ID into the currently open group.
def makenamedlink
Link the previously captured group/data ID into the currently open group, but under a different name.
def sameID
Return True of ID1 and ID2 point to the same group/data.
def opensourcegroup
If the current node is a linked to another group or data, then open the group or data that it is linked to.
def link
Returns the item which the current item links to, or None if the current item is not linked.
def inquirefile
Return the filename for the current file.
def linkexternal
Return the filename for the external link if there is one, otherwise return None.
def isexternalgroup
Return the filename for the external link if there is one, otherwise return None.
def show
Print the structure of a NeXus file from the current node.
Additional Inherited Members
Public Attributes inherited from nxs.napi.NeXus
isopen
mode
handle
Properties inherited from nxs.napi.NeXus
path = property(_getpath,doc="Unix-style path to node")
longpath
Detailed Description
Structure-based interface to the NeXus file API.
Usage::
file = NeXusTree(filename, ['r','rw','w'])
open the NeXus file root = file.readfile()
read the structure of the NeXus file. This returns a NeXus tree. file.writefile(root)
write a NeXus tree to the file. data = file.readpath(path)
read data from a particular path
Example::
nx = NeXusTree('REF_L_1346.nxs','r') tree = nx.readfile() for entry in tree.NXentry: process(entry) copy = NeXusTree('modified.nxs','w') copy.writefile(tree)
Note that the large datasets are not loaded immediately. Instead, the when the data set is requested, the file is reopened, the data read, and the file closed again. open/close are available for when we want to read/write slabs without the overhead of moving the file cursor each time. The NXdata objects in the returned tree hold the object values.
Definition at line 298 of file tree.py.
Member Function Documentation
def nxs.tree.NeXusTree.readfile (self)
Read the NeXus file structure from the file and return a tree of NXobjects.
Large datasets are not read until they are needed.
Definition at line 307 of file tree.py.
References nxs.tree.NeXusTree._readgroup(), nxs.napi.NeXus.close(), nxs.napi.NeXus.open(), and nxs.napi.NeXus.openpath().
def nxs.tree.NeXusTree.readpath (self, path)
Return the data on a particular file path.
Returns a numpy array containing the data, a python scalar, or a string depending on the shape and storage class.
Definition at line 340 of file tree.py.
References nxs.tree.NeXusTree._readchildren(), nxs.tree.NeXusTree._readdata(), nxs.tree.NeXusTree._readgroup(), nxs.tree.NeXusTree._readlinks(), nxs.tree.NeXusTree._skipgroups, nxs.tree.NeXusTree._writeattrs(), nxs.tree.NeXusTree._writedata(), nxs.tree.NeXusTree._writegroup(), nxs.napi.NeXus.closedata(), nxs.napi.NeXus.closegroup(), nxs.napi.NeXus.compmakedata(), nxs.napi.NeXus.getattr(), nxs.napi.NeXus.getattrs(), nxs.napi.NeXus.getdata(), nxs.napi.NeXus.getdataID(), nxs.napi.NeXus.getgroupID(), nxs.napi.NeXus.getgroupinfo(), nxs.napi.NeXus.getinfo(), nxs.napi.NeXus.getnextentry(), nxs.napi.NeXus.makedata(), nxs.napi.NeXus.makegroup(), nxs.napi.NeXus.makelink(), nxs.napi.NeXus.open(), nxs.napi.NeXus.opendata(), nxs.napi.NeXus.opengroup(), nxs.napi.NeXus.openpath(), nxs.napi.NeXus.path, nxs.napi.NeXus.putattr(), and nxs.napi.NeXus.putdata().
def nxs.tree.NeXusTree.writefile (self, tree)
Write the NeXus file structure to a file.
The file is assumed to start empty. Updating individual objects can be done using the napi interface, with nx.handle as the nexus file handle.
Definition at line 325 of file tree.py.
References nxs.tree.NeXusTree._writegroup(), nxs.tree.NeXusTree._writelinks(), nxs.napi.NeXus.close(), and nxs.napi.NeXus.open().
The documentation for this class was generated from the following file:
bindings/python/nxs/tree.py