NeXus: nxs.napi.NeXus Class Reference
nxs.napi.NeXus Class Reference
Public Member Functions
def __init__
Open the NeXus file returning a handle.
def __del__
Be sure to close the file before deleting the last reference.
def __str__
Return a string representation of the NeXus file handle.
def open
Opens the NeXus file handle if it is not already open.
def close
Close the NeXus file associated with handle.
def flush
Flush all data to the NeXus file.
def setnumberformat
Set the output format for the numbers of the given type (only applies to XML).
def makegroup
Create the group nxclass:name.
def openpath
Open a particular group '/path/to/group'.
def opengrouppath
Open a particular group '/path/to/group', or the dataset containing the group if the path refers to a dataset.
def opengroup
Open the group nxclass:name.
def closegroup
Close the currently open group.
def getgroupinfo
Query the currently open group returning the tuple numentries, name, nxclass.
def initgroupdir
Reset getnextentry to return the first entry in the group.
def getnextentry
Return the next entry in the group as name,nxclass tuple.
def getentries
Return a dictionary of the groups[name]=type below the existing open one.
def entries
Iterator of entries.
def getrawinfo
Returns the tuple dimensions,type for the currently open dataset.
def getinfo
Returns the tuple dimensions,type for the currently open dataset.
def opendata
Open the named data set within the current group.
def closedata
Close the currently open data set.
def makedata
Create a data element of the given type and shape.
def compmakedata
Create a data element of the given dimensions and type.
def getdata
Return the data.
def getslab
Get a slab from the data array.
def putdata
Write data into the currently open data block.
def putslab
Put a slab into the data array.
def initattrdir
Reset the getnextattr list to the first attribute.
def getattrinfo
Returns the number of attributes for the currently open group/data object.
def getnextattr
Returns the name, length, and data type for the next attribute.
def getattr
Returns the value of the named attribute.
def putattr
Saves the named attribute.
def getattrs
Returns a dicitonary of the attributes on the current node.
def attrs
Iterate over attributes.
def getgroupID
Return the id of the current group so we can link to it later.
def getdataID
Return the id of the current data so we can link to it later.
def makelink
Link the previously captured group/data ID into the currently open group.
def makenamedlink
Link the previously captured group/data ID into the currently open group, but under a different name.
def sameID
Return True of ID1 and ID2 point to the same group/data.
def opensourcegroup
If the current node is a linked to another group or data, then open the group or data that it is linked to.
def link
Returns the item which the current item links to, or None if the current item is not linked.
def inquirefile
Return the filename for the current file.
def linkexternal
Return the filename for the external link if there is one, otherwise return None.
def isexternalgroup
Return the filename for the external link if there is one, otherwise return None.
def show
Print the structure of a NeXus file from the current node.
Public Attributes
isopen
mode
handle
Properties
path = property(_getpath,doc="Unix-style path to node")
longpath
Detailed Description
Definition at line 287 of file napi.py.
Constructor & Destructor Documentation
def nxs.napi.NeXus.__init__ (self, filename, mode = 'r')
Open the NeXus file returning a handle.
mode can be one of the following: nxs.ACC_READ 'r' open a file read-only nxs.ACC_RDWR 'rw' open a file read/write nxs.ACC_CREATE 'w' open a file write nxs.ACC_CREATE4 'w4' open a Nexus file with HDF4 nxs.ACC_CREATE5 'w5' open a Nexus file with HDF5 nxs.ACC_CREATEXML 'wx' open a Nexus file with XML
Raises ValueError if the open mode is invalid.
Raises NeXusError if the file could not be opened, with the filename as part of the error message.
Corresponds to NXopen(filename,mode,&handle)
Definition at line 311 of file napi.py.
def nxs.napi.NeXus.__del__ (self)
Be sure to close the file before deleting the last reference.
Definition at line 347 of file napi.py.
References nxs.napi.NeXus.close(), and nxs.napi.NeXus.isopen.
Member Function Documentation
def nxs.napi.NeXus.__str__ (self)
Return a string representation of the NeXus file handle.
Definition at line 355 of file napi.py.
def nxs.napi.NeXus.attrs (self)
Iterate over attributes.
for name,value in file.attrs(): process(name,value)
This automatically reads the attributes of the group/data. Do not change the active group/data while processing the list.
This does not correspond to an existing NeXus API function, but combines the work of attrinfo/initattrdir/getnextattr/getattr.
Definition at line 1208 of file napi.py.
References nxs.napi.NeXus.getattr(), nxs.napi.NeXus.getattrinfo(), nxs.napi.NeXus.getnextattr(), and nxs.napi.NeXus.initattrdir().
Referenced by nxs.napi.NeXus.getattrs(), and nxs.napi.NeXus.show().
def nxs.napi.NeXus.close (self)
Close the NeXus file associated with handle.
Raises NeXusError if file could not be closed.
Corresponds to NXclose(&handle)
Definition at line 389 of file napi.py.
References nxs.napi.NeXus._indata, nxs.napi.NeXus._path, nxs.napi.NeXus.handle, and nxs.napi.NeXus.isopen.
Referenced by nxs.napi.NeXus.__del__(), nxs.tree.NeXusTree.readfile(), and nxs.tree.NeXusTree.writefile().
def nxs.napi.NeXus.closedata (self)
Close the currently open data set.
Raises NeXusError if this fails (e.g., because no dataset is open).
Corresponds to NXclosedata(handle)
Definition at line 869 of file napi.py.
References nxs.napi.NeXus._indata, nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.openpath(), and nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.closegroup (self)
Close the currently open group.
Raises NeXusError if the group could not be closed.
Corresponds to NXclosegroup(handle)
Definition at line 604 of file napi.py.
References nxs.napi.NeXus._indata, nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.openpath(), and nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.compmakedata (self, name, dtype = None, shape = None, mode = 'lzw', chunks = None)
Create a data element of the given dimensions and type.
See getinfo for details on types. Compression mode is one of 'none', 'lzw', 'rle' or 'huffman'. chunks gives the alignment of the compressed chunks in the data file. There should be one chunk size for each dimension in the data.
Defaults to mode='lzw' with chunk size set to the length of the fastest varying dimension.
Raises ValueError if it fails.
Corresponds to NXmakedata(handle,name,type,rank,dims).
Definition at line 924 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.makedata(), and nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.entries (self)
Iterator of entries.
for name,nxclass in nxs.entries(): process(name,nxclass)
This automatically opens the corresponding group/data for you, and closes it when you are done. Do not rely on any paths remaining open between entries as we restore the current path each time.
This does not correspond to an existing NeXus API function, but instead combines the work of initgroupdir/getnextentry and open/close on data and group. Entries in nxs.H4SKIP are ignored.
Definition at line 742 of file napi.py.
References nxs.napi.NeXus.getgroupinfo(), nxs.napi.NeXus.getnextentry(), nxs.napi.NeXus.initgroupdir(), nxs.napi.NeXus.opendata(), nxs.napi.NeXus.opengroup(), nxs.napi.NeXus.openpath(), and nxs.napi.NeXus.path.
Referenced by nxs.tree.NXobject.__repr__(), and nxs.napi.NeXus.show().
def nxs.napi.NeXus.flush (self)
Flush all data to the NeXus file.
Raises NeXusError if this fails.
Corresponds to NXflush(&handle)
Definition at line 408 of file napi.py.
References nxs.napi.NeXus.handle.
def nxs.napi.NeXus.getattr (self, name, length, dtype)
Returns the value of the named attribute.
Requires length and data type from getnextattr to allocate the appropriate amount of space for the attribute.
Corresponds to NXgetattr(handle,name,data,&length,&storage)
Definition at line 1120 of file napi.py.
References nxs.napi.NeXus._loc(), nxs.napi.NeXus._poutput(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.attrs(), nxs.napi.NeXus.link(), and nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.getattrinfo (self)
Returns the number of attributes for the currently open group/data object.
Do not call getnextattr() more than this number of times.
Raises NeXusError if this fails.
Corresponds to NXgetattrinfo(handl, &n)
Definition at line 1068 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.attrs(), and nxs.napi.NeXus.link().
def nxs.napi.NeXus.getattrs (self)
Returns a dicitonary of the attributes on the current node.
This is a second form of attrs(self).
Definition at line 1189 of file napi.py.
References nxs.tree.NXobject.attrs, nxs.napi.NeXus.attrs(), and nxs.tree.NXlink.attrs.
Referenced by nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.getdata (self)
Return the data.
If data is a string (1-D char array), a python string is returned. If data is a scalar (1-D numeric array of length 1), a python scalar is returned. If data is a string array, a numpy array of type 'S#' where # is the maximum string length is returned. If data is a numeric array, a numpy array is returned.
Raises ValueError if this fails.
Corresponds to NXgetdata(handle, data)
Definition at line 957 of file napi.py.
References nxs.napi.NeXus._loc(), nxs.napi.NeXus._poutput(), nxs.napi.NeXus.getinfo(), and nxs.napi.NeXus.handle.
Referenced by nxs.tree.NeXusTree.readpath(), and nxs.napi.NeXus.show().
def nxs.napi.NeXus.getdataID (self)
Return the id of the current data so we can link to it later.
Raises NeXusError
Corresponds to NXgetdataID(handle, &ID)
Definition at line 1244 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.getentries (self)
Return a dictionary of the groups[name]=type below the existing open one.
Raises NeXusError if this fails.
Definition at line 700 of file napi.py.
References nxs.napi.NeXus.getnextentry(), nxs.napi.NeXus.initgroupdir(), and nxs.napi.NeXus.path.
def nxs.napi.NeXus.getgroupID (self)
Return the id of the current group so we can link to it later.
Raises NeXusError
Corresponds to NXgetgroupID(handle, &ID)
Definition at line 1227 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.getgroupinfo (self)
Query the currently open group returning the tuple numentries, name, nxclass.
Raises ValueError if the group could not be opened.
Corresponds to NXgetgroupinfo(handle)
Note: corrects error in HDF5 where getgroupinfo returns the entire path rather than the group name. Use the path attribute to get a sensible value of path.
Definition at line 628 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.entries(), and nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.getinfo (self)
Returns the tuple dimensions,type for the currently open dataset.
Dimensions is an integer array whose length corresponds to the rank of the dataset and whose elements are the size of the individual dimensions. Storage type is returned as a string, with 'char' for a stored string, '[u]int[8|16|32]' for various integer values or 'float[32|64]' for floating point values. No support for complex values.
Unlike getrawinfo(), the length of the stored string is returned rather than the size of the string storage area.
Raises NeXusError if this fails.
Note that this is the recommended way to establish if you have a dataset open.
Corresponds to NXgetinfo(handle, &rank, dims, &storage), but with storage converted from HDF values to numpy compatible strings, and rank implicit in the length of the returned dimensions.
Definition at line 823 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.getdata(), nxs.tree.NeXusTree.readpath(), and nxs.napi.NeXus.show().
def nxs.napi.NeXus.getnextattr (self)
Returns the name, length, and data type for the next attribute.
Call getattrinfo to determine the number of attributes before calling getnextattr. Data type is returned as a string. See getinfo for details. Length is the number of elements in the attribute.
Raises NeXusError if NeXus returns ERROR or EOD.
Corresponds to NXgetnextattr(handle,name,&length,&storage) but with storage converted from HDF values to numpy compatible strings.
Note: NeXus API documentation seems to say that length is the number of bytes required to store the entire attribute.
Definition at line 1095 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.attrs(), and nxs.napi.NeXus.link().
def nxs.napi.NeXus.getnextentry (self)
Return the next entry in the group as name,nxclass tuple.
If end of data is reached this returns the tuple (None, None)
Raises NeXusError if this fails.
Corresponds to NXgetnextentry(handle,name,nxclass,&storage).
This function doesn't return the storage class for data entries since getinfo returns shape and storage, both of which are required to read the data.
Note that HDF4 files can have entries in the file with classes that don't need to be processed. If the file follows the standard NeXus DTDs then skip any entry for which nxclass.startswith('NX') is False. For non-conforming files, skip those entries with nxclass in nxs.H4SKIP.
Definition at line 677 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.entries(), nxs.napi.NeXus.getentries(), and nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.getrawinfo (self)
Returns the tuple dimensions,type for the currently open dataset.
Dimensions is an integer array whose length corresponds to the rank of the dataset and whose elements are the size of the individual dimensions. Storage type is returned as a string, with 'char' for a stored string, '[u]int[8|16|32]' for various integer values or 'float[32|64]' for floating point values. No support for complex values.
Unlike getinfo(), the size of the string storage area is returned rather than the length of the stored string.
Raises NeXusError if this fails.
Corresponds to NXgetrawinfo(handle, &rank, dims, &storage), but with storage converted from HDF values to numpy compatible strings, and rank implicit in the length of the returned dimensions.
Definition at line 786 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.getslab(), nxs.napi.NeXus.putdata(), and nxs.napi.NeXus.putslab().
def nxs.napi.NeXus.getslab (self, slab_offset, slab_shape)
Get a slab from the data array.
Offsets are 0-origin. Shape can be inferred from the data. Offset and shape must each have one entry per dimension.
Raises ValueError if this fails.
Corresponds to NXgetslab(handle,data,offset,shape)
Definition at line 980 of file napi.py.
References nxs.napi.NeXus._loc(), nxs.napi.NeXus._poutput(), nxs.napi.NeXus.getrawinfo(), and nxs.napi.NeXus.handle.
def nxs.napi.NeXus.initattrdir (self)
Reset the getnextattr list to the first attribute.
Raises NeXusError if this fails.
Corresponds to NXinitattrdir(handle)
Definition at line 1050 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.attrs(), and nxs.napi.NeXus.link().
def nxs.napi.NeXus.initgroupdir (self)
Reset getnextentry to return the first entry in the group.
Raises NeXusError if this fails.
Corresponds to NXinitgroupdir(handle)
Definition at line 650 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.entries(), and nxs.napi.NeXus.getentries().
def nxs.napi.NeXus.inquirefile (self, maxnamelen = MAXPATHLEN)
Return the filename for the current file.
This may be different from the file that was opened (file.filename) if the current group is an external link to another file.
Raises NeXusError if this fails.
Corresponds to NXinquirefile(&handle,file,len)
Definition at line 1353 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.show().
def nxs.napi.NeXus.isexternalgroup (self, name, nxclass, maxnamelen = MAXPATHLEN)
Return the filename for the external link if there is one, otherwise return None.
Corresponds to NXisexternalgroup(&handle,name,nxclass,file,len)
Definition at line 1391 of file napi.py.
References nxs.napi.NeXus._loc(), nxs.napi.NeXus.handle, and nxs.napi.NeXus.path.
def nxs.napi.NeXus.link (self)
Returns the item which the current item links to, or None if the current item is not linked.
This is equivalent to scanning the attributes for target and returning it if target is not equal to self.
This does not correspond to an existing NeXus API function, but combines the work of attrinfo/initattrdir/getnextattr/getattr.
Definition at line 1326 of file napi.py.
References nxs.napi.NeXus.getattr(), nxs.napi.NeXus.getattrinfo(), nxs.napi.NeXus.getnextattr(), nxs.napi.NeXus.initattrdir(), and nxs.napi.NeXus.path.
Referenced by nxs.napi.NeXus.show().
def nxs.napi.NeXus.linkexternal (self, name, nxclass, url)
Return the filename for the external link if there is one, otherwise return None.
Raises NeXusError if link fails.
Corresponds to NXisexternalgroup(&handle,name,nxclass,file,len)
Definition at line 1373 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
def nxs.napi.NeXus.makedata (self, name, dtype = None, shape = None)
Create a data element of the given type and shape.
See getinfo for details on types. This does not open the data for writing.
Set the first dimension to nxs.UNLIMITED, for extensible data sets, and use putslab to write individual slabs.
Raises ValueError if it fails.
Corresponds to NXmakedata(handle,name,type,rank,dims)
Definition at line 892 of file napi.py.
References nxs.napi.NeXus._loc(), nxs.napi.NeXus.compmakedata(), and nxs.napi.NeXus.handle.
Referenced by nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.makegroup (self, name, nxclass)
Create the group nxclass:name.
Raises NeXusError if the group could not be created.
Corresponds to NXmakegroup(handle, name, nxclass)
Definition at line 442 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.makelink (self, ID)
Link the previously captured group/data ID into the currently open group.
Raises NeXusError
Corresponds to NXmakelink(handle, &ID)
Definition at line 1262 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.makenamedlink (self, name, ID)
Link the previously captured group/data ID into the currently open group, but under a different name.
Raises NeXusError
Corresponds to NXmakenamedlink(handle,name,&ID)
Definition at line 1278 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
def nxs.napi.NeXus.open (self)
Opens the NeXus file handle if it is not already open.
Raises NeXusError if the file could not be opened.
Corresponds to NXopen(filename,mode,&handle)
Definition at line 367 of file napi.py.
References nxs.napi.NeXus._indata, nxs.napi.NeXus._path, nxs.napi.NeXus.handle, nxs.napi.NeXus.isopen, and nxs.napi.NeXus.mode.
Referenced by nxs.tree.NeXusTree.readfile(), nxs.tree.NeXusTree.readpath(), and nxs.tree.NeXusTree.writefile().
def nxs.napi.NeXus.opendata (self, name)
Open the named data set within the current group.
Raises ValueError if could not open the dataset.
Corresponds to NXopendata(handle, name)
Definition at line 847 of file napi.py.
References nxs.napi.NeXus._indata, nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.entries(), nxs.napi.NeXus.openpath(), and nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.opengroup (self, name, nxclass = None)
Open the group nxclass:name.
If the nxclass is not specified this will search for it.
Raises NeXusError if the group could not be opened.
Corresponds to NXopengroup(handle, name, nxclass)
Definition at line 584 of file napi.py.
References nxs.napi.NeXus.__getnxclass(), nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.napi.NeXus.entries(), nxs.napi.NeXus.openpath(), and nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.opengrouppath (self, path)
Open a particular group '/path/to/group', or the dataset containing the group if the path refers to a dataset.
Paths can be relative to the currently open group.
Raises ValueError.
Corresponds to NXopengrouppath(handle, path)
Definition at line 570 of file napi.py.
References nxs.napi.NeXus._openpath().
def nxs.napi.NeXus.openpath (self, path)
Open a particular group '/path/to/group'.
Paths can be absolute or relative to the currently open group. If openpath fails, then currently open path may not be different from the starting path. For better performation the types can be specified as well using '/path:type1/to:type2/group:type3' which will prevent searching the file for the types associated with the supplied names.
Raises ValueError.
Corresponds to NXopenpath(handle, path)
Definition at line 465 of file napi.py.
References nxs.napi.NeXus.__getnxclass(), nxs.napi.NeXus._indata, nxs.napi.NeXus._openpath(), nxs.napi.NeXus._path, nxs.napi.NeXus.closedata(), nxs.napi.NeXus.closegroup(), nxs.napi.NeXus.opendata(), nxs.napi.NeXus.opengroup(), and nxs.napi.NeXus.path.
Referenced by nxs.napi.NeXus.entries(), nxs.tree.NeXusTree.readfile(), nxs.tree.NeXusTree.readpath(), and nxs.napi.NeXus.show().
def nxs.napi.NeXus.opensourcegroup (self)
If the current node is a linked to another group or data, then open the group or data that it is linked to.
Note: it is unclear how can we tell if we are linked, other than perhaps the existence of a 'target' attribute in the current item.
Raises NeXusError.
Corresponds to NXopensourcegroup(handle)
Definition at line 1311 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
def nxs.napi.NeXus.putattr (self, name, value, dtype = None)
Saves the named attribute.
The attribute value is a string or a scalar.
Raises TypeError if the value type is incorrect. Raises NeXusError if the attribute could not be saved.
Corresponds to NXputattr(handle,name,data,length,storage)
Note length is the number of elements to write rather than the number of bytes to write.
Definition at line 1147 of file napi.py.
References nxs.napi.NeXus._loc(), and nxs.napi.NeXus.handle.
Referenced by nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.putdata (self, data)
Write data into the currently open data block.
Raises ValueError if this fails.
Corresponds to NXputdata(handle, data)
Definition at line 1004 of file napi.py.
References nxs.napi.NeXus._loc(), nxs.napi.NeXus._pinput(), nxs.napi.NeXus.getrawinfo(), and nxs.napi.NeXus.handle.
Referenced by nxs.tree.NeXusTree.readpath().
def nxs.napi.NeXus.putslab (self, data, slab_offset, slab_shape)
Put a slab into the data array.
Offsets are 0-origin. Shape can be inferred from the data. Offset and shape must each have one entry per dimension.
Raises ValueError if this fails.
Corresponds to NXputslab(handle,data,offset,shape)
Definition at line 1025 of file napi.py.
References nxs.napi.NeXus._loc(), nxs.napi.NeXus._pinput(), nxs.napi.NeXus.getrawinfo(), and nxs.napi.NeXus.handle.
def nxs.napi.NeXus.sameID (self, ID1, ID2)
Return True of ID1 and ID2 point to the same group/data.
This should not raise any errors.
Corresponds to NXsameID(handle,&ID1,&ID2)
Definition at line 1293 of file napi.py.
References nxs.napi.NeXus.handle.
def nxs.napi.NeXus.setnumberformat (self, type, format)
Set the output format for the numbers of the given type (only applies to XML).
Raises ValueError if the number format is incorrect.
Corresponds to NXsetnumberformat(&handle,type,format)
Definition at line 424 of file napi.py.
References nxs.napi.NeXus.handle.
def nxs.napi.NeXus.show (self, path = None, indent = 0)
Print the structure of a NeXus file from the current node.
TODO: Break this into a tree walker and a visitor.
Definition at line 1488 of file napi.py.
References nxs.napi.NeXus._show(), nxs.tree.NXobject.attrs, nxs.napi.NeXus.attrs(), nxs.tree.NXlink.attrs, nxs.napi.NeXus.entries(), nxs.tree.NXgroup.entries, nxs.tree.NXlinkgroup.entries, nxs.napi.NeXus.getdata(), nxs.napi.NeXus.getinfo(), nxs.napi.NeXus.inquirefile(), nxs.napi.NeXus.link(), nxs.napi.NeXus.openpath(), and nxs.napi.NeXus.path.
Member Data Documentation
nxs.napi.NeXus.handle
Definition at line 320 of file napi.py.
Referenced by nxs.napi.NeXus.close(), nxs.napi.NeXus.closedata(), nxs.napi.NeXus.closegroup(), nxs.napi.NeXus.compmakedata(), nxs.napi.NeXus.flush(), nxs.napi.NeXus.getattr(), nxs.napi.NeXus.getattrinfo(), nxs.napi.NeXus.getdata(), nxs.napi.NeXus.getdataID(), nxs.napi.NeXus.getgroupID(), nxs.napi.NeXus.getgroupinfo(), nxs.napi.NeXus.getinfo(), nxs.napi.NeXus.getnextattr(), nxs.napi.NeXus.getnextentry(), nxs.napi.NeXus.getrawinfo(), nxs.napi.NeXus.getslab(), nxs.napi.NeXus.initattrdir(), nxs.napi.NeXus.initgroupdir(), nxs.napi.NeXus.inquirefile(), nxs.napi.NeXus.isexternalgroup(), nxs.napi.NeXus.linkexternal(), nxs.napi.NeXus.makedata(), nxs.napi.NeXus.makegroup(), nxs.napi.NeXus.makelink(), nxs.napi.NeXus.makenamedlink(), nxs.napi.NeXus.open(), nxs.napi.NeXus.opendata(), nxs.napi.NeXus.opengroup(), nxs.napi.NeXus.opensourcegroup(), nxs.napi.NeXus.putattr(), nxs.napi.NeXus.putdata(), nxs.napi.NeXus.putslab(), nxs.napi.NeXus.sameID(), and nxs.napi.NeXus.setnumberformat().
nxs.napi.NeXus.isopen
Definition at line 312 of file napi.py.
Referenced by nxs.napi.NeXus.__del__(), nxs.napi.NeXus.close(), and nxs.napi.NeXus.open().
nxs.napi.NeXus.mode
Definition at line 319 of file napi.py.
Referenced by nxs.napi.NeXus.open().
Property Documentation
nxs.napi.NeXus.longpath static
Initial value:
property(_getlongpath, doc="Unix-style path including " \
                        + "nxclass to the node")
Definition at line 340 of file napi.py.
nxs.napi.NeXus.path = property(_getpath,doc="Unix-style path to node") static
Definition at line 335 of file napi.py.
Referenced by nxs.napi.NeXus.entries(), nxs.napi.NeXus.getentries(), nxs.napi.NeXus.isexternalgroup(), nxs.napi.NeXus.link(), nxs.napi.NeXus.openpath(), nxs.tree.NeXusTree.readpath(), and nxs.napi.NeXus.show().
The documentation for this class was generated from the following file:
bindings/python/nxs/napi.py