NeXus: nxs.tree.PylabPlotter Class Reference
nxs.tree.PylabPlotter Class Reference
Matplotlib plotter class for NeXus data.
Public Member Functions
def plot
Plot the data entry.
Static Public Member Functions
def show
Detailed Description
Matplotlib plotter class for NeXus data.
Definition at line 1803 of file tree.py.
Member Function Documentation
def nxs.tree.PylabPlotter.plot (self, signal, axes, title, errors, fmt, xmin, xmax, ymin, ymax, zmin, zmax, opts)
Plot the data entry.
Raises NeXusError if the data cannot be plotted.
Definition at line 1813 of file tree.py.
References nxs.tree.centers(), and nxs.tree.label().
Referenced by nxs.tree.NXgroup.logplot(), and nxs.tree.NXgroup.oplot().
def nxs.tree.PylabPlotter.show () static
Definition at line 1934 of file tree.py.
The documentation for this class was generated from the following file:
bindings/python/nxs/tree.py