#ifndef QXRDNIDAQSYNCWAVEFORMOUTPUTPTR_H
#define QXRDNIDAQSYNCWAVEFORMOUTPUTPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdNIDAQSyncWaveformOutput)

#endif // QXRDNIDAQSYNCWAVEFORMOUTPUTPTR_H
