#ifndef QXRDNIDAQSYNCDETECTOROUTPUTPTR_H
#define QXRDNIDAQSYNCDETECTOROUTPUTPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QxrdNIDAQSyncDetectorOutput)

#endif // QXRDNIDAQSYNCDETECTOROUTPUTPTR_H
