NXvalidate: org.nexusformat.nxvalidate.NXvalidateBasicGui Class Reference
org.nexusformat.nxvalidate.NXvalidateBasicGui Class Reference
Public Member Functions
NXvalidateBasicGui ()
TreeModel parseXML (String filename) throws Exception
void actionPerformed (ActionEvent e)
Static Public Member Functions
static void main (String[] args)
Detailed Description
Definition at line 60 of file NXvalidateBasicGui.java.
Constructor & Destructor Documentation
org.nexusformat.nxvalidate.NXvalidateBasicGui.NXvalidateBasicGui ()
Definition at line 87 of file NXvalidateBasicGui.java.
Member Function Documentation
void org.nexusformat.nxvalidate.NXvalidateBasicGui.actionPerformed (ActionEvent e)
Definition at line 237 of file NXvalidateBasicGui.java.
References org.nexusformat.nxvalidate.NXvalidate.getReports(), org.nexusformat.nxvalidate.NXvalidate.setConvertNxs(), org.nexusformat.nxvalidate.NXvalidate.setKeepTemp(), org.nexusformat.nxvalidate.NXvalidate.setNXSFile(), and org.nexusformat.nxvalidate.NXvalidate.setSchematron().
static void org.nexusformat.nxvalidate.NXvalidateBasicGui.main (String[] args) static
Definition at line 368 of file NXvalidateBasicGui.java.
TreeModel org.nexusformat.nxvalidate.NXvalidateBasicGui.parseXML (String filename) throws Exception
Definition at line 229 of file NXvalidateBasicGui.java.
References org.nexusformat.nxvalidate.XMLIconTreeHandler.getRoot().
The documentation for this class was generated from the following file:
applications/NXvalidate/src/org/nexusformat/nxvalidate/NXvalidateBasicGui.java