NXvalidate: org.nexusformat.nxvalidate.TreeUtils Class Reference
org.nexusformat.nxvalidate.TreeUtils Class Reference
Public Member Functions
void hideGoodNodes (JTree tree)
boolean hasBadChildren (NXNodeMapper node)
void showGoodNodes (JTree tree)
String getTreePath (JTree tree)
NXNodeMapper getBaseNode (JTree tree)
File getNXDLFile (JTree tree)
File getReducedFile (JTree tree)
Document getReducedDoc (JTree tree)
Document getResultsDoc (JTree tree)
File getResultsFile (JTree tree)
void setNXDLFile (JTree tree, File file)
void setReducedFile (JTree tree, File file)
void setReducedDoc (JTree tree, Document doc)
void setResultsDoc (JTree tree, Document doc)
void setResultsFile (JTree tree, File file)
void setValidated (JTree tree, File file)
Detailed Description
Author:
Stephen Rankin
Definition at line 39 of file TreeUtils.java.
Member Function Documentation
NXNodeMapper org.nexusformat.nxvalidate.TreeUtils.getBaseNode (JTree tree)
Definition at line 182 of file TreeUtils.java.
Referenced by org.nexusformat.nxvalidate.TreeUtils.hideGoodNodes(), and org.nexusformat.nxvalidate.TreeUtils.showGoodNodes().
File org.nexusformat.nxvalidate.TreeUtils.getNXDLFile (JTree tree)
Definition at line 190 of file TreeUtils.java.
References org.nexusformat.nxvalidate.NXNodeMapper.getNXDLFile().
Document org.nexusformat.nxvalidate.TreeUtils.getReducedDoc (JTree tree)
Definition at line 206 of file TreeUtils.java.
References org.nexusformat.nxvalidate.NXNodeMapper.getReducedDoc().
File org.nexusformat.nxvalidate.TreeUtils.getReducedFile (JTree tree)
Definition at line 198 of file TreeUtils.java.
References org.nexusformat.nxvalidate.NXNodeMapper.getReducedFile().
Document org.nexusformat.nxvalidate.TreeUtils.getResultsDoc (JTree tree)
Definition at line 214 of file TreeUtils.java.
References org.nexusformat.nxvalidate.NXNodeMapper.getResultsDoc().
File org.nexusformat.nxvalidate.TreeUtils.getResultsFile (JTree tree)
Definition at line 222 of file TreeUtils.java.
References org.nexusformat.nxvalidate.NXNodeMapper.getResultsFile().
String org.nexusformat.nxvalidate.TreeUtils.getTreePath (JTree tree)
Definition at line 157 of file TreeUtils.java.
References org.nexusformat.nxvalidate.NXNodeMapper.toString().
boolean org.nexusformat.nxvalidate.TreeUtils.hasBadChildren (NXNodeMapper node)
Definition at line 126 of file TreeUtils.java.
Referenced by org.nexusformat.nxvalidate.NXNodeMapper.hasBadChildren().
void org.nexusformat.nxvalidate.TreeUtils.hideGoodNodes (JTree tree)
Definition at line 44 of file TreeUtils.java.
References org.nexusformat.nxvalidate.NXNodeMapper.checkBadNode(), org.nexusformat.nxvalidate.TreeUtils.getBaseNode(), and org.nexusformat.nxvalidate.NXNodeMapper.getParent().
void org.nexusformat.nxvalidate.TreeUtils.setNXDLFile (JTree tree, File file)
Definition at line 230 of file TreeUtils.java.
References org.nexusformat.nxvalidate.NXNodeMapper.setNXDLFile().
void org.nexusformat.nxvalidate.TreeUtils.setReducedDoc (JTree tree, Document doc)
Definition at line 242 of file TreeUtils.java.
References org.nexusformat.nxvalidate.NXNodeMapper.setReducedDoc().
void org.nexusformat.nxvalidate.TreeUtils.setReducedFile (JTree tree, File file)
Definition at line 236 of file TreeUtils.java.
References org.nexusformat.nxvalidate.NXNodeMapper.setReducedFile().
void org.nexusformat.nxvalidate.TreeUtils.setResultsDoc (JTree tree, Document doc)
Definition at line 248 of file TreeUtils.java.
References org.nexusformat.nxvalidate.NXNodeMapper.setResultsDoc().
Referenced by org.nexusformat.nxvalidate.FileActions.validateFile().
void org.nexusformat.nxvalidate.TreeUtils.setResultsFile (JTree tree, File file)
Definition at line 254 of file TreeUtils.java.
References org.nexusformat.nxvalidate.NXNodeMapper.setResultsFile().
Referenced by org.nexusformat.nxvalidate.FileActions.validateFile().
void org.nexusformat.nxvalidate.TreeUtils.setValidated (JTree tree, File file)
Definition at line 260 of file TreeUtils.java.
References org.nexusformat.nxvalidate.NXNodeMapper.getResultsFile(), and org.nexusformat.nxvalidate.NXNodeMapper.setValidatedNode().
Referenced by org.nexusformat.nxvalidate.FileActions.validateFile().
void org.nexusformat.nxvalidate.TreeUtils.showGoodNodes (JTree tree)
Definition at line 139 of file TreeUtils.java.
References org.nexusformat.nxvalidate.TreeUtils.getBaseNode(), and org.nexusformat.nxvalidate.NXNodeMapper.toString().
The documentation for this class was generated from the following file:
applications/NXvalidate/src/org/nexusformat/nxvalidate/TreeUtils.java