NXvalidate: org.nexusformat.nxvalidate.ValidatorUtils Class Reference
org.nexusformat.nxvalidate.ValidatorUtils Class Reference
A class the wraps the conversion and validation processes.
Public Member Functions
ValidatorUtils (File nxsFile, String nxconvertCommand)
void setReduced (File reduced)
Set the File object pointing to the reduced NEXUS file.
File getReduced ()
Get the File object pointing to the reduced NEXUS file.
void setNXS (File nxsFile)
Set the File object pointing to the NEXUS file.
File getNXS ()
Get the File object pointing to the NEXUS file.
void setSchematron (File schematronFile)
Set the File object pointing to the Schematron file that contains the rules for checking the reduced document.
File getSchematron ()
Get the File object pointing to the Schematron file that contains the rules for checking the reduced document.
void doConversion (boolean convertNxs)
Set a flag that indicates that the conversion of a NEXUS file to a reduced document should be performed (true).
void setKeepTemp (boolean keepTemp)
Set a flag that indicates that the temporary files (such as the reduced document and the validation results) should be kept (true).
File validate () throws NXvalidateException
This methods performs the validation using the NEXUS (or reduced) file and the Schematron file.
Detailed Description
A class the wraps the conversion and validation processes.
Author:
Stephen Rankin
Definition at line 37 of file ValidatorUtils.java.
Constructor & Destructor Documentation
org.nexusformat.nxvalidate.ValidatorUtils.ValidatorUtils (File nxsFile, String nxconvertCommand)
Definition at line 47 of file ValidatorUtils.java.
Member Function Documentation
void org.nexusformat.nxvalidate.ValidatorUtils.doConversion (boolean convertNxs)
Set a flag that indicates that the conversion of a NEXUS file to a reduced document should be performed (true).
Parameters:
convertNxs the conversion flag.
Definition at line 117 of file ValidatorUtils.java.
File org.nexusformat.nxvalidate.ValidatorUtils.getNXS ()
Get the File object pointing to the NEXUS file.
Returns:
the NEXUS File object.
Definition at line 87 of file ValidatorUtils.java.
File org.nexusformat.nxvalidate.ValidatorUtils.getReduced ()
Get the File object pointing to the reduced NEXUS file.
Returns:
the reduced NEXUS File object.
Definition at line 68 of file ValidatorUtils.java.
File org.nexusformat.nxvalidate.ValidatorUtils.getSchematron ()
Get the File object pointing to the Schematron file that contains the rules for checking the reduced document.
Returns:
the Schematron File object.
Definition at line 107 of file ValidatorUtils.java.
void org.nexusformat.nxvalidate.ValidatorUtils.setKeepTemp (boolean keepTemp)
Set a flag that indicates that the temporary files (such as the reduced document and the validation results) should be kept (true).
Parameters:
keepTemp the keep temp files flag.
Definition at line 128 of file ValidatorUtils.java.
void org.nexusformat.nxvalidate.ValidatorUtils.setNXS (File nxsFile)
Set the File object pointing to the NEXUS file.
Parameters:
nxsFile the NEXUS File object.
Definition at line 77 of file ValidatorUtils.java.
void org.nexusformat.nxvalidate.ValidatorUtils.setReduced (File reduced)
Set the File object pointing to the reduced NEXUS file.
Parameters:
reduced the reduced NEXUS File object.
Definition at line 58 of file ValidatorUtils.java.
Referenced by org.nexusformat.nxvalidate.FileActions.validateFile().
void org.nexusformat.nxvalidate.ValidatorUtils.setSchematron (File schematronFile)
Set the File object pointing to the Schematron file that contains the rules for checking the reduced document.
Parameters:
schematronFile the Schematron File object.
Definition at line 97 of file ValidatorUtils.java.
Referenced by org.nexusformat.nxvalidate.FileActions.validateFile().
File org.nexusformat.nxvalidate.ValidatorUtils.validate () throws NXvalidateException
This methods performs the validation using the NEXUS (or reduced) file and the Schematron file.
The returned file is the results file.
Returns:
the results file as a File object.
Exceptions:
NXvalidateException
Definition at line 138 of file ValidatorUtils.java.
References org.nexusformat.nxvalidate.NXconvert.convert().
Referenced by org.nexusformat.nxvalidate.FileActions.validateFile().
The documentation for this class was generated from the following file:
applications/NXvalidate/src/org/nexusformat/nxvalidate/ValidatorUtils.java