NXvalidate: org.nexusformat.nxvalidate.FileActions Class Reference
org.nexusformat.nxvalidate.FileActions Class Reference
Public Member Functions
FileActions (NXvalidateFrame frame, JTree jTree, DocumentBuilder builder, NXReducedToTree domTree, NXNodeMapper root)
void setWhich (int which)
void setNXSFile (File nxsFile)
void setNXDLFile (File nxdlFile)
void setNXConvertFile (String nxconvertCommand)
String getNXConvertFile ()
void setReducedFile (File reducedFile)
void setResultsDoc (Document resultsDoc)
void setReducedDoc (Document reducedDoc)
void setDataFiles (File[] dataFiles)
boolean getValidateResult ()
ArrayList< String > getDataFileList ()
void setDataFileList (ArrayList< String > dataFileList)
File getSaveDirectory ()
void setSaveDirectory (File saveDirectory)
boolean getConversionResult ()
ArrayList< String > getBadDataFileList ()
void validateFile ()
void loadFile ()
void bulkCheck ()
void bulkLoad ()
void bulkValidate ()
void saveResults (File directory)
void run ()
Detailed Description
Author:
Stephen Rankin
Definition at line 51 of file FileActions.java.
Constructor & Destructor Documentation
org.nexusformat.nxvalidate.FileActions.FileActions (NXvalidateFrame frame, JTree jTree, DocumentBuilder builder, NXReducedToTree domTree, NXNodeMapper root)
Definition at line 79 of file FileActions.java.
Member Function Documentation
void org.nexusformat.nxvalidate.FileActions.bulkCheck ()
Definition at line 305 of file FileActions.java.
Referenced by org.nexusformat.nxvalidate.FileActions.run().
void org.nexusformat.nxvalidate.FileActions.bulkLoad ()
Definition at line 325 of file FileActions.java.
References org.nexusformat.nxvalidate.FileActions.loadFile(), and org.nexusformat.nxvalidate.NXReducedToTree.updateTree().
Referenced by org.nexusformat.nxvalidate.FileActions.run().
void org.nexusformat.nxvalidate.FileActions.bulkValidate ()
Definition at line 337 of file FileActions.java.
References org.nexusformat.nxvalidate.FileActions.loadFile(), org.nexusformat.nxvalidate.NXReducedToTree.updateTree(), and org.nexusformat.nxvalidate.FileActions.validateFile().
Referenced by org.nexusformat.nxvalidate.FileActions.run().
ArrayList<String> org.nexusformat.nxvalidate.FileActions.getBadDataFileList ()
Definition at line 156 of file FileActions.java.
boolean org.nexusformat.nxvalidate.FileActions.getConversionResult ()
Definition at line 152 of file FileActions.java.
ArrayList<String> org.nexusformat.nxvalidate.FileActions.getDataFileList ()
Definition at line 136 of file FileActions.java.
String org.nexusformat.nxvalidate.FileActions.getNXConvertFile ()
Definition at line 112 of file FileActions.java.
File org.nexusformat.nxvalidate.FileActions.getSaveDirectory ()
Definition at line 144 of file FileActions.java.
boolean org.nexusformat.nxvalidate.FileActions.getValidateResult ()
Definition at line 132 of file FileActions.java.
void org.nexusformat.nxvalidate.FileActions.loadFile ()
Definition at line 234 of file FileActions.java.
References org.nexusformat.nxvalidate.NXconvert.convert(), org.nexusformat.nxvalidate.NXNodeMapper.insert(), org.nexusformat.nxvalidate.NXNodeMapper.setNXDLFile(), org.nexusformat.nxvalidate.NXNodeMapper.setReducedDoc(), org.nexusformat.nxvalidate.NXNodeMapper.setReducedFile(), and org.nexusformat.nxvalidate.NXNodeMapper.setRoot().
Referenced by org.nexusformat.nxvalidate.FileActions.bulkLoad(), org.nexusformat.nxvalidate.FileActions.bulkValidate(), and org.nexusformat.nxvalidate.FileActions.run().
void org.nexusformat.nxvalidate.FileActions.run ()
Definition at line 396 of file FileActions.java.
References org.nexusformat.nxvalidate.FileActions.bulkCheck(), org.nexusformat.nxvalidate.FileActions.bulkLoad(), org.nexusformat.nxvalidate.FileActions.bulkValidate(), org.nexusformat.nxvalidate.FileActions.loadFile(), org.nexusformat.nxvalidate.FileActions.saveResults(), org.nexusformat.nxvalidate.NXReducedToTree.updateTree(), and org.nexusformat.nxvalidate.FileActions.validateFile().
void org.nexusformat.nxvalidate.FileActions.saveResults (File directory)
Definition at line 368 of file FileActions.java.
References org.nexusformat.nxvalidate.NXNodeMapper.getReducedFile(), and org.nexusformat.nxvalidate.NXNodeMapper.getResultsFile().
Referenced by org.nexusformat.nxvalidate.FileActions.run().
void org.nexusformat.nxvalidate.FileActions.setDataFileList (ArrayList< String > dataFileList)
Definition at line 140 of file FileActions.java.
void org.nexusformat.nxvalidate.FileActions.setDataFiles (File[] dataFiles)
Definition at line 128 of file FileActions.java.
void org.nexusformat.nxvalidate.FileActions.setNXConvertFile (String nxconvertCommand)
Definition at line 108 of file FileActions.java.
void org.nexusformat.nxvalidate.FileActions.setNXDLFile (File nxdlFile)
Definition at line 104 of file FileActions.java.
void org.nexusformat.nxvalidate.FileActions.setNXSFile (File nxsFile)
Definition at line 100 of file FileActions.java.
void org.nexusformat.nxvalidate.FileActions.setReducedDoc (Document reducedDoc)
Definition at line 124 of file FileActions.java.
void org.nexusformat.nxvalidate.FileActions.setReducedFile (File reducedFile)
Definition at line 116 of file FileActions.java.
void org.nexusformat.nxvalidate.FileActions.setResultsDoc (Document resultsDoc)
Definition at line 120 of file FileActions.java.
void org.nexusformat.nxvalidate.FileActions.setSaveDirectory (File saveDirectory)
Definition at line 148 of file FileActions.java.
void org.nexusformat.nxvalidate.FileActions.setWhich (int which)
Definition at line 96 of file FileActions.java.
void org.nexusformat.nxvalidate.FileActions.validateFile ()
Definition at line 160 of file FileActions.java.
References org.nexusformat.nxvalidate.SVRLNodeFilter.getBadNodeList(), org.nexusformat.nxvalidate.SVRLNodeFilter.resetNodes(), org.nexusformat.nxvalidate.SVRLNodeFilter.setDocument(), org.nexusformat.nxvalidate.SVRLNodeFilter.setFilterDocument(), org.nexusformat.nxvalidate.ValidatorUtils.setReduced(), org.nexusformat.nxvalidate.TreeUtils.setResultsDoc(), org.nexusformat.nxvalidate.TreeUtils.setResultsFile(), org.nexusformat.nxvalidate.ValidatorUtils.setSchematron(), org.nexusformat.nxvalidate.TreeUtils.setValidated(), and org.nexusformat.nxvalidate.ValidatorUtils.validate().
Referenced by org.nexusformat.nxvalidate.FileActions.bulkValidate(), and org.nexusformat.nxvalidate.FileActions.run().
The documentation for this class was generated from the following file:
applications/NXvalidate/src/org/nexusformat/nxvalidate/FileActions.java