NXvalidate: org.nexusformat.nxvalidate.NXvalidate Class Reference
org.nexusformat.nxvalidate.NXvalidate Class Reference
Public Member Functions
ArrayList< Report > getReports ()
ArrayList< File > getFilenames ()
void setFilenames (ArrayList< String > filenames)
void setNXSFile (File file)
File getSchematron ()
void setSchematron (File schematronFile)
boolean isKeepTemp ()
void setKeepTemp (boolean keepTemp)
boolean isConvertNxs ()
void setConvertNxs (boolean convertNxs)
int getVerbose ()
void setVerbose (int verbose)
File getReduced ()
File setReduced (File reduced)
Static Public Member Functions
static String getVersion ()
static void main (String[] args)
Detailed Description
Definition at line 33 of file NXvalidate.java.
Member Function Documentation
ArrayList<File> org.nexusformat.nxvalidate.NXvalidate.getFilenames ()
Definition at line 57 of file NXvalidate.java.
File org.nexusformat.nxvalidate.NXvalidate.getReduced ()
Definition at line 105 of file NXvalidate.java.
ArrayList<Report> org.nexusformat.nxvalidate.NXvalidate.getReports ()
Definition at line 53 of file NXvalidate.java.
Referenced by org.nexusformat.nxvalidate.NXvalidateBasicGui.actionPerformed().
File org.nexusformat.nxvalidate.NXvalidate.getSchematron ()
Definition at line 69 of file NXvalidate.java.
int org.nexusformat.nxvalidate.NXvalidate.getVerbose ()
Definition at line 93 of file NXvalidate.java.
static String org.nexusformat.nxvalidate.NXvalidate.getVersion () static
Definition at line 101 of file NXvalidate.java.
boolean org.nexusformat.nxvalidate.NXvalidate.isConvertNxs ()
Definition at line 85 of file NXvalidate.java.
boolean org.nexusformat.nxvalidate.NXvalidate.isKeepTemp ()
Definition at line 77 of file NXvalidate.java.
static void org.nexusformat.nxvalidate.NXvalidate.main (String[] args) static
Definition at line 252 of file NXvalidate.java.
void org.nexusformat.nxvalidate.NXvalidate.setConvertNxs (boolean convertNxs)
Definition at line 89 of file NXvalidate.java.
Referenced by org.nexusformat.nxvalidate.NXvalidateBasicGui.actionPerformed().
void org.nexusformat.nxvalidate.NXvalidate.setFilenames (ArrayList< String > filenames)
Definition at line 61 of file NXvalidate.java.
void org.nexusformat.nxvalidate.NXvalidate.setKeepTemp (boolean keepTemp)
Definition at line 81 of file NXvalidate.java.
Referenced by org.nexusformat.nxvalidate.NXvalidateBasicGui.actionPerformed().
void org.nexusformat.nxvalidate.NXvalidate.setNXSFile (File file)
Definition at line 65 of file NXvalidate.java.
Referenced by org.nexusformat.nxvalidate.NXvalidateBasicGui.actionPerformed().
File org.nexusformat.nxvalidate.NXvalidate.setReduced (File reduced)
Definition at line 109 of file NXvalidate.java.
void org.nexusformat.nxvalidate.NXvalidate.setSchematron (File schematronFile)
Definition at line 73 of file NXvalidate.java.
Referenced by org.nexusformat.nxvalidate.NXvalidateBasicGui.actionPerformed().
void org.nexusformat.nxvalidate.NXvalidate.setVerbose (int verbose)
Definition at line 97 of file NXvalidate.java.
The documentation for this class was generated from the following file:
applications/NXvalidate/src/org/nexusformat/nxvalidate/NXvalidate.java