NXvalidate: org.nexusformat.nxvalidate.CheckNexusFileType Class Reference
org.nexusformat.nxvalidate.CheckNexusFileType Class Reference
Public Member Functions
CheckNexusFileType ()
boolean checkNexusFile (File file)
Checks to see if a file is a HDF/Nexus file and returns true if it is.
boolean checkHDF5 (File file) throws FileNotFoundException, IOException
Checks to see if a file is a HDF5 file and returns true if it is.
boolean checkHDF4 (File file) throws FileNotFoundException, IOException
Checks to see if a file is a HDF4 file and returns true if it is.
boolean checkNXDLFile (File file)
Checks to see if a file is a Nexus definition file and returns true if it is.
Detailed Description
Author:
Stephen Rankin
Definition at line 47 of file CheckNexusFileType.java.
Constructor & Destructor Documentation
org.nexusformat.nxvalidate.CheckNexusFileType.CheckNexusFileType ()
Definition at line 52 of file CheckNexusFileType.java.
Member Function Documentation
boolean org.nexusformat.nxvalidate.CheckNexusFileType.checkHDF4 (File file) throws FileNotFoundException, IOException
Checks to see if a file is a HDF4 file and returns true if it is.
Parameters:
file the input file to check.
Returns:
boolean which is true if the file is a HDF4 file.
Exceptions:
FileNotFoundException
IOException
Definition at line 128 of file CheckNexusFileType.java.
Referenced by org.nexusformat.nxvalidate.CheckNexusFileType.checkNexusFile().
boolean org.nexusformat.nxvalidate.CheckNexusFileType.checkHDF5 (File file) throws FileNotFoundException, IOException
Checks to see if a file is a HDF5 file and returns true if it is.
Parameters:
file the input file to check.
Returns:
boolean which is true if the file is a HDF5 file.
Exceptions:
FileNotFoundException
IOException
Definition at line 95 of file CheckNexusFileType.java.
Referenced by org.nexusformat.nxvalidate.CheckNexusFileType.checkNexusFile().
boolean org.nexusformat.nxvalidate.CheckNexusFileType.checkNexusFile (File file)
Checks to see if a file is a HDF/Nexus file and returns true if it is.
The method checks for HDF4, HDF5 and Nexus XML files.
Parameters:
file the input file to check.
Returns:
boolean which is true if the file is a HDF/Nexus file.
Exceptions:
FileNotFoundException
IOException
Definition at line 71 of file CheckNexusFileType.java.
References org.nexusformat.nxvalidate.CheckNexusFileType.checkHDF4(), and org.nexusformat.nxvalidate.CheckNexusFileType.checkHDF5().
boolean org.nexusformat.nxvalidate.CheckNexusFileType.checkNXDLFile (File file)
Checks to see if a file is a Nexus definition file and returns true if it is.
Parameters:
file the input file to check.
Returns:
boolean which is true if the file is a Nexus definition file.
Exceptions:
FileNotFoundException
IOException
Definition at line 203 of file CheckNexusFileType.java.
The documentation for this class was generated from the following file:
applications/NXvalidate/src/org/nexusformat/nxvalidate/CheckNexusFileType.java