NXvalidate: org.nexusformat.nxvalidate.SVRLitem Class Reference
org.nexusformat.nxvalidate.SVRLitem Class Reference
Public Member Functions
SVRLitem (final Node node)
String toString ()
String getLocation ()
String getType ()
String getTest ()
String getMessage ()
Static Public Member Functions
static boolean hasLocation (final Node candidate)
static String getLocation (final Node node)
Detailed Description
Definition at line 35 of file SVRLitem.java.
Constructor & Destructor Documentation
org.nexusformat.nxvalidate.SVRLitem.SVRLitem (final Node node)
Definition at line 45 of file SVRLitem.java.
Member Function Documentation
String org.nexusformat.nxvalidate.SVRLitem.getLocation ()
Definition at line 70 of file SVRLitem.java.
Referenced by org.nexusformat.nxvalidate.SVRLitem.hasLocation(), and org.nexusformat.nxvalidate.SVRLitem.toString().
static String org.nexusformat.nxvalidate.SVRLitem.getLocation (final Node node) static
Definition at line 167 of file SVRLitem.java.
String org.nexusformat.nxvalidate.SVRLitem.getMessage ()
Definition at line 87 of file SVRLitem.java.
String org.nexusformat.nxvalidate.SVRLitem.getTest ()
Definition at line 83 of file SVRLitem.java.
String org.nexusformat.nxvalidate.SVRLitem.getType ()
Definition at line 79 of file SVRLitem.java.
static boolean org.nexusformat.nxvalidate.SVRLitem.hasLocation (final Node candidate) static
Definition at line 153 of file SVRLitem.java.
References org.nexusformat.nxvalidate.SVRLitem.getLocation().
String org.nexusformat.nxvalidate.SVRLitem.toString ()
Definition at line 52 of file SVRLitem.java.
References org.nexusformat.nxvalidate.SVRLitem.getLocation().
The documentation for this class was generated from the following file:
applications/NXvalidate/src/org/nexusformat/nxvalidate/SVRLitem.java