NXvalidate: org.nexusformat.nxvalidate.TextPaneStyle Class Reference
org.nexusformat.nxvalidate.TextPaneStyle Class Reference
Public Member Functions
TextPaneStyle (JTextPane pane)
void updateTextPane (NXNodeMapper node)
Detailed Description
Author:
Stephen Rankin
Definition at line 43 of file TextPaneStyle.java.
Constructor & Destructor Documentation
org.nexusformat.nxvalidate.TextPaneStyle.TextPaneStyle (JTextPane pane)
Definition at line 47 of file TextPaneStyle.java.
Member Function Documentation
void org.nexusformat.nxvalidate.TextPaneStyle.updateTextPane (NXNodeMapper node)
Definition at line 131 of file TextPaneStyle.java.
References org.nexusformat.nxvalidate.NXNodeMapper.getAttributeList(), org.nexusformat.nxvalidate.NXNodeMapper.getBadNode(), org.nexusformat.nxvalidate.NXNodeMapper.getValue(), org.nexusformat.nxvalidate.NXNodeMapper.getWarnNode(), and org.nexusformat.nxvalidate.NXNodeMapper.toString().
The documentation for this class was generated from the following file:
applications/NXvalidate/src/org/nexusformat/nxvalidate/TextPaneStyle.java