NXvalidate: org.nexusformat.nxvalidate.UserSettings Class Reference
org.nexusformat.nxvalidate.UserSettings Class Reference
Public Member Functions
UserSettings ()
void loadUserSettings () throws FileNotFoundException, IOException
void saveUserSettings ()
String getNXconvert ()
void setNXconvert (String nxconvertCommand)
boolean foundNXconvert ()
Detailed Description
Author:
Stephen Rankin
Definition at line 44 of file UserSettings.java.
Constructor & Destructor Documentation
org.nexusformat.nxvalidate.UserSettings.UserSettings ()
Definition at line 52 of file UserSettings.java.
Member Function Documentation
boolean org.nexusformat.nxvalidate.UserSettings.foundNXconvert ()
Definition at line 134 of file UserSettings.java.
Referenced by org.nexusformat.nxvalidate.UserSettings.loadUserSettings(), and org.nexusformat.nxvalidate.UserSettings.setNXconvert().
String org.nexusformat.nxvalidate.UserSettings.getNXconvert ()
Definition at line 120 of file UserSettings.java.
void org.nexusformat.nxvalidate.UserSettings.loadUserSettings () throws FileNotFoundException, IOException
Definition at line 58 of file UserSettings.java.
References org.nexusformat.nxvalidate.UserSettings.foundNXconvert().
void org.nexusformat.nxvalidate.UserSettings.saveUserSettings ()
Definition at line 93 of file UserSettings.java.
void org.nexusformat.nxvalidate.UserSettings.setNXconvert (String nxconvertCommand)
Definition at line 124 of file UserSettings.java.
References org.nexusformat.nxvalidate.UserSettings.foundNXconvert().
The documentation for this class was generated from the following file:
applications/NXvalidate/src/org/nexusformat/nxvalidate/UserSettings.java