NeXusJavaBindings: ncsa.hdf.hdflib.HDFException Class Reference
ncsa.hdf.hdflib.HDFException Class Reference
Public Member Functions
HDFException ()
HDFException (String s)
HDFException (int err)
String getMessage ()
Static Public Attributes
static final String OutOfMemoryMessage = "ERROR: HDF Library: Out of memory"
static final String HDFExceptionMessage = "ERROR: HDF Library Error"
static final String HDFMessage = "ERROR: Unknown HDF Error"
Detailed Description
The class HDFException returns errors from the HDF library.
Two sub-classes of HDFException are defined:
HDFLibraryException – errors raised the HDF library code
HDFJavaException – errors raised the HDF Java wrapper code
These exceptions will be sub-classed to represent specific error conditions, as needed.
The only specific exception currently defined is HDFNotImplementedException, indicating a function that is part of the HDF API, but which cannot or will not be implemented for Java.
Definition at line 36 of file HDFException.java.
Constructor & Destructor Documentation
ncsa.hdf.hdflib.HDFException.HDFException ()
Definition at line 46 of file HDFException.java.
ncsa.hdf.hdflib.HDFException.HDFException (String s)
Definition at line 50 of file HDFException.java.
ncsa.hdf.hdflib.HDFException.HDFException (int err)
Definition at line 54 of file HDFException.java.
Member Function Documentation
String ncsa.hdf.hdflib.HDFException.getMessage ()
Reimplemented in ncsa.hdf.hdflib.HDFNotImplementedException, and ncsa.hdf.hdflib.HDFJavaException.
Definition at line 58 of file HDFException.java.
Referenced by org.nexusformat.NexusFile.getattr(), org.nexusformat.NexusFile.getdata(), org.nexusformat.NexusFile.getslab(), org.nexusformat.NexusFile.putattr(), org.nexusformat.NexusFile.putdata(), and org.nexusformat.NexusFile.putslab().
Member Data Documentation
final String ncsa.hdf.hdflib.HDFException.HDFExceptionMessage = "ERROR: HDF Library Error" static
Definition at line 40 of file HDFException.java.
final String ncsa.hdf.hdflib.HDFException.HDFMessage = "ERROR: Unknown HDF Error" static
Definition at line 41 of file HDFException.java.
final String ncsa.hdf.hdflib.HDFException.OutOfMemoryMessage = "ERROR: HDF Library: Out of memory" static
Definition at line 39 of file HDFException.java.
The documentation for this class was generated from the following file:
bindings/java/ncsa/hdf/hdflib/HDFException.java