NeXusJavaBindings: bindings/java/native/handle.c File Reference
handle.c File Reference
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "handle.h"
Functions
int HHMakeHandle (void *pData)
void * HHGetPointer (int handle)
void HHRemoveHandle (int handle)
Function Documentation
void* HHGetPointer (int handle)
Definition at line 48 of file handle.c.
Referenced by Java_org_nexusformat_NexusFile_close(), Java_org_nexusformat_NexusFile_initattrdir(), Java_org_nexusformat_NexusFile_initgroupdir(), Java_org_nexusformat_NexusFile_nextattr(), Java_org_nexusformat_NexusFile_nextentry(), Java_org_nexusformat_NexusFile_nxclosedata(), Java_org_nexusformat_NexusFile_nxclosegroup(), Java_org_nexusformat_NexusFile_nxcompress(), Java_org_nexusformat_NexusFile_nxflush(), Java_org_nexusformat_NexusFile_nxgetattr(), Java_org_nexusformat_NexusFile_nxgetdata(), Java_org_nexusformat_NexusFile_nxgetdataid(), Java_org_nexusformat_NexusFile_nxgetgroupid(), Java_org_nexusformat_NexusFile_nxgetinfo(), Java_org_nexusformat_NexusFile_nxgetinfo64(), Java_org_nexusformat_NexusFile_nxgetpath(), Java_org_nexusformat_NexusFile_nxgetslab(), Java_org_nexusformat_NexusFile_nxgetslab64(), Java_org_nexusformat_NexusFile_nxinquirefile(), Java_org_nexusformat_NexusFile_nxisexternaldataset(), Java_org_nexusformat_NexusFile_nxisexternalgroup(), Java_org_nexusformat_NexusFile_nxlinkexternal(), Java_org_nexusformat_NexusFile_nxlinkexternaldataset(), Java_org_nexusformat_NexusFile_nxmakecompdata(), Java_org_nexusformat_NexusFile_nxmakecompdata64(), Java_org_nexusformat_NexusFile_nxmakedata(), Java_org_nexusformat_NexusFile_nxmakedata64(), Java_org_nexusformat_NexusFile_nxmakegroup(), Java_org_nexusformat_NexusFile_nxmakelink(), Java_org_nexusformat_NexusFile_nxmakenamedlink(), Java_org_nexusformat_NexusFile_nxopendata(), Java_org_nexusformat_NexusFile_nxopengroup(), Java_org_nexusformat_NexusFile_nxopengrouppath(), Java_org_nexusformat_NexusFile_nxopenpath(), Java_org_nexusformat_NexusFile_nxopensourcegroup(), Java_org_nexusformat_NexusFile_nxputattr(), Java_org_nexusformat_NexusFile_nxputdata(), Java_org_nexusformat_NexusFile_nxputslab(), Java_org_nexusformat_NexusFile_nxputslab64(), and Java_org_nexusformat_NexusFile_nxsetnumberformat().
int HHMakeHandle (void * pData)
Definition at line 28 of file handle.c.
References MAXHANDLE.
Referenced by Java_org_nexusformat_NexusFile_init(), and Java_org_nexusformat_NexusFile_nxflush().
void HHRemoveHandle (int handle)
Definition at line 55 of file handle.c.
Referenced by Java_org_nexusformat_NexusFile_close(), and Java_org_nexusformat_NexusFile_nxflush().