#ifndef QXRDSYNCHRONIZEDACQUISITIONDIALOG_PTR_H
#define QXRDSYNCHRONIZEDACQUISITIONDIALOG_PTR_H

class QxrdSynchronizedAcquisitionDialog;

typedef QxrdSynchronizedAcquisitionDialog *QxrdSynchronizedAcquisitionDialogPtr;

#endif // QXRDSYNCHRONIZEDACQUISITIONDIALOG_PTR_H
