#ifndef QXRDACQUISITIONTRIGGERDIALOG_PTR_H
#define QXRDACQUISITIONTRIGGERDIALOG_PTR_H

class QxrdAcquisitionTriggerDialog;

typedef QxrdAcquisitionTriggerDialog *QxrdAcquisitionTriggerDialogPtr;

#endif // QXRDACQUISITIONTRIGGERDIALOG_PTR_H
