#ifndef QXRDDEBUG_H
#define QXRDDEBUG_H

#include "qcepdebug.h"

enum {
  DEBUG_ACQUIRE     = (LAST_CEP_DEBUG + 1),
  DEBUG_PROCESS,
  DEBUG_FILES,
  DEBUG_PERFORM,
  DEBUG_IMAGES,
  DEBUG_PERKINELMER,
  DEBUG_PERKINELMERIDLING,
  DEBUG_EXITWAIT,
  DEBUG_DELAY_ACQ,
  DEBUG_BROWSER,
  DEBUG_ACQUIRETIME,
  DEBUG_INTEGRATOR,
  DEBUG_TRIGGER,
  DEBUG_EXTRAINPUTS,
  DEBUG_LOGSCRIPTS,
  DEBUG_PLUGINS,
  DEBUG_FITTING,
  DEBUG_NOPARALLEL,
  DEBUG_HISTOGRAM,
  DEBUG_CALIBRANT,
  DEBUG_PILATUS
};

class QxrdDebugDictionary : public QcepDebugDictionary {
public:
  QxrdDebugDictionary();
};

#endif // QXRDDEBUG_H
