NeXus: bindings/f77/napif.f File Reference
napif.f File Reference
Functions/Subroutines
INTEGER function truelen (STRING)
Return length of a string, ignoring trailing blanks.
subroutine extract_string (ISTRING, LENMAX, STRING)
Convert FORTRAN string STRING into NULL terminated C string ISTRING.
subroutine replace_string (STRING, ISTRING)
Convert NULL terminated C string ISTRING to FORTRAN string STRING.
INTEGER function nxopen (FILENAME, ACCESS_METHOD, FILEID)
Wrapper routines for NXAPI interface.
INTEGER function nxclose (FILEID)
INTEGER function nxflush (FILEID)
INTEGER function nxmakegroup (FILEID, VGROUP, NXCLASS)
INTEGER function nxopengroup (FILEID, VGROUP, NXCLASS)
INTEGER function nxopenpath (FILEID, PATH)
INTEGER function nxgetpath (FILEID, PATH)
INTEGER function nxopengrouppath (FILEID, PATH)
INTEGER function nxclosegroup (FILEID)
INTEGER function nxmakedata (FILEID, LABEL, DATATYPE, RANK, DIM)
INTEGER function nxcompmakedata (FILEID, LABEL, DATATYPE, RANK, DIM, COMPRESSION_TYPE, CHUNK)
INTEGER function nxopendata (FILEID, LABEL)
INTEGER function nxsetnumberformat (FILEID, ITYPE, FORMAT)
INTEGER function nxcompress (FILEID, COMPR_TYPE)
INTEGER function nxclosedata (FILEID)
INTEGER function nxgetdata (FILEID, DATA)
INTEGER function nxgetchardata (FILEID, DATA)
INTEGER function nxgetslab (FILEID, DATA, START, SIZE)
INTEGER function nxgetattr (FILEID, NAME, DATA, DATALEN, TYPE)
INTEGER function nxgetcharattr (FILEID, NAME, DATA, DATALEN, TYPE)
INTEGER function nxputdata (FILEID, DATA)
INTEGER function nxputchardata (FILEID, DATA)
INTEGER function nxputslab (FILEID, DATA, START, SIZE)
INTEGER function nxputattr (FILEID, NAME, DATA, DATALEN, TYPE)
INTEGER function nxputcharattr (FILEID, NAME, DATA, DATALEN, TYPE)
INTEGER function nxgetinfo (FILEID, RANK, DIM, DATATYPE)
INTEGER function nxgetnextentry (FILEID, NAME, CLASS, DATATYPE)
INTEGER function nxgetnextattr (FILEID, PNAME, ILENGTH, ITYPE)
INTEGER function nxgetgroupid (FILEID, LINK)
INTEGER function nxgetdataid (FILEID, LINK)
INTEGER function nxmakelink (FILEID, LINK)
INTEGER function nxmakenamedlink (FILEID, PNAME, LINK)
INTEGER function nxopensourcegroup (FILEID)
LOGICAL function nxsameid (FILEID, LINK1, LINK2)
INTEGER function nxgetgroupinfo (FILEID, NUM, NAME, CLASS)
INTEGER function nxinitgroupdir (FILEID)
INTEGER function nxgetattrinfo (FILEID, NUM)
INTEGER function nxinitattrdir (FILEID)
INTEGER function nxisexternalgroup (FILEID, VGROUP, NXCLASS, NXURL)
INTEGER function nxinquirefile (FILEID, NXFILE)
INTEGER function nxlinkexternal (FILEID, VGROUP, NXCLASS, NXURL)
Function/Subroutine Documentation
subroutine extract_string (integer*1, dimension(lenmax) ISTRING, integer LENMAX, character*(*) STRING)
Convert FORTRAN string STRING into NULL terminated C string ISTRING.
Definition at line 80 of file napif.f.
References truelen().
Referenced by nxcompmakedata(), nxgetattr(), nxgetcharattr(), nxisexternalgroup(), nxlinkexternal(), nxmakedata(), nxmakegroup(), nxmakenamedlink(), nxopen(), nxopendata(), nxopengroup(), nxopengrouppath(), nxopenpath(), nxputattr(), nxputcharattr(), nxputchardata(), and nxsetnumberformat().
INTEGER function nxclose (integer, dimension(*) FILEID)
Definition at line 128 of file napif.f.
Referenced by __napif_test.f__().
INTEGER function nxclosedata (integer, dimension(*) FILEID)
Definition at line 241 of file napif.f.
Referenced by __napif_test.f__().
INTEGER function nxclosegroup (integer, dimension(*) FILEID)
Definition at line 189 of file napif.f.
Referenced by __napif_test.f__().
INTEGER function nxcompmakedata (integer, dimension(*) FILEID, character*(*) LABEL, integer DATATYPE, integer RANK, integer, dimension(*) DIM, integer COMPRESSION_TYPE, integer, dimension(*) CHUNK)
Definition at line 204 of file napif.f.
References extract_string().
Referenced by __napif_test.f__().
INTEGER function nxcompress (integer, dimension(*) FILEID, integer COMPR_TYPE)
Definition at line 235 of file napif.f.
INTEGER function nxflush (integer, dimension(*) FILEID)
Definition at line 134 of file napif.f.
Referenced by __napif_test.f__().
INTEGER function nxgetattr (integer, dimension(*) FILEID, character*(*) NAME, integer, dimension(*) DATA, integer DATALEN, integer TYPE)
Definition at line 288 of file napif.f.
References extract_string().
Referenced by __napif_test.f__().
INTEGER function nxgetattrinfo (integer, dimension(*) FILEID, integer NUM)
Definition at line 471 of file napif.f.
Referenced by __napif_test.f__().
INTEGER function nxgetcharattr (integer, dimension(*) FILEID, character*(*) NAME, character*(*) DATA, integer DATALEN, integer TYPE)
Definition at line 298 of file napif.f.
References extract_string(), and replace_string().
Referenced by __napif_test.f__().
INTEGER function nxgetchardata (integer, dimension(*) FILEID, character*(*) DATA)
Definition at line 253 of file napif.f.
References replace_string().
Referenced by __napif_test.f__().
INTEGER function nxgetdata (integer, dimension(*) FILEID, integer, dimension(*) DATA)
Definition at line 247 of file napif.f.
Referenced by __napif_test.f__().
INTEGER function nxgetdataid (integer, dimension(*) FILEID, integer, dimension(*) LINK)
Definition at line 417 of file napif.f.
Referenced by __napif_test.f__().
INTEGER function nxgetgroupid (integer, dimension(*) FILEID, integer, dimension(*) LINK)
Definition at line 411 of file napif.f.
Referenced by __napif_test.f__().
INTEGER function nxgetgroupinfo (integer, dimension(*) FILEID, integer NUM, character*(*) NAME, character*(*) CLASS)
Definition at line 455 of file napif.f.
References replace_string().
Referenced by __napif_test.f__().
INTEGER function nxgetinfo (integer, dimension(*) FILEID, integer RANK, integer, dimension(*) DIM, integer DATATYPE)
Definition at line 378 of file napif.f.
Referenced by __napif_test.f__(), nxgetslab(), and nxputslab().
INTEGER function nxgetnextattr (integer, dimension(*) FILEID, character*(*) PNAME, integer ILENGTH, integer ITYPE)
Definition at line 402 of file napif.f.
References replace_string().
Referenced by __napif_test.f__().
INTEGER function nxgetnextentry (integer, dimension(*) FILEID, character*(*) NAME, character*(*) CLASS, integer DATATYPE)
Definition at line 391 of file napif.f.
References replace_string().
Referenced by __napif_test.f__().
INTEGER function nxgetpath (integer, dimension(*) FILEID, character*(*) PATH)
Definition at line 169 of file napif.f.
References replace_string().
INTEGER function nxgetslab (integer, dimension(*) FILEID, integer, dimension(*) DATA, integer, dimension(*) START, integer, dimension(*) SIZE)
Definition at line 271 of file napif.f.
References nxgetinfo().
Referenced by __napif_test.f__().
INTEGER function nxinitattrdir (integer, dimension(*) FILEID)
Definition at line 477 of file napif.f.
INTEGER function nxinitgroupdir (integer, dimension(*) FILEID)
Definition at line 465 of file napif.f.
INTEGER function nxinquirefile (integer, dimension(*) FILEID, character*(*) NXFILE)
Definition at line 497 of file napif.f.
References replace_string().
INTEGER function nxisexternalgroup (integer, dimension(*) FILEID, character*(*) VGROUP, character*(*) NXCLASS, character*(*) NXURL)
Definition at line 483 of file napif.f.
References extract_string(), and replace_string().
INTEGER function nxlinkexternal (integer, dimension(*) FILEID, character*(*) VGROUP, character*(*) NXCLASS, character*(*) NXURL)
Definition at line 507 of file napif.f.
References extract_string().
INTEGER function nxmakedata (integer, dimension(*) FILEID, character*(*) LABEL, integer DATATYPE, integer RANK, integer, dimension(*) DIM)
Definition at line 195 of file napif.f.
References extract_string().
Referenced by __napif_test.f__().
INTEGER function nxmakegroup (integer, dimension(*) FILEID, character*(*) VGROUP, character*(*) NXCLASS)
Definition at line 140 of file napif.f.
References extract_string().
Referenced by __napif_test.f__().
INTEGER function nxmakelink (integer, dimension(*) FILEID, integer, dimension(*) LINK)
Definition at line 423 of file napif.f.
Referenced by __napif_test.f__().
INTEGER function nxmakenamedlink (integer, dimension(*) FILEID, character*(*) PNAME, integer, dimension(*) LINK)
Definition at line 429 of file napif.f.
References extract_string().
INTEGER function nxopen (character*(*) FILENAME, integer ACCESS_METHOD, integer, dimension(*) FILEID)
Wrapper routines for NXAPI interface.
Definition at line 118 of file napif.f.
References extract_string().
Referenced by __napif_test.f__().
INTEGER function nxopendata (integer, dimension(*) FILEID, character*(*) LABEL)
Definition at line 217 of file napif.f.
References extract_string().
Referenced by __napif_test.f__().
INTEGER function nxopengroup (integer, dimension(*) FILEID, character*(*) VGROUP, character*(*) NXCLASS)
Definition at line 150 of file napif.f.
References extract_string().
Referenced by __napif_test.f__().
INTEGER function nxopengrouppath (integer, dimension(*) FILEID, character*(*) PATH)
Definition at line 180 of file napif.f.
References extract_string().
INTEGER function nxopenpath (integer, dimension(*) FILEID, character*(*) PATH)
Definition at line 160 of file napif.f.
References extract_string().
Referenced by __napif_test.f__().
INTEGER function nxopensourcegroup (integer, dimension(*) FILEID)
Definition at line 438 of file napif.f.
INTEGER function nxputattr (integer, dimension(*) FILEID, character*(*) NAME, integer, dimension(*) DATA, integer DATALEN, integer TYPE)
Definition at line 355 of file napif.f.
References extract_string().
Referenced by __napif_test.f__().
INTEGER function nxputcharattr (integer, dimension(*) FILEID, character*(*) NAME, character*(*) DATA, integer DATALEN, integer TYPE)
Definition at line 365 of file napif.f.
References extract_string().
Referenced by __napif_test.f__().
INTEGER function nxputchardata (integer, dimension(*) FILEID, character*(*) DATA)
Definition at line 329 of file napif.f.
References extract_string().
Referenced by __napif_test.f__().
INTEGER function nxputdata (integer, dimension(*) FILEID, integer, dimension(*) DATA)
Definition at line 323 of file napif.f.
Referenced by __napif_test.f__().
INTEGER function nxputslab (integer, dimension(*) FILEID, integer, dimension(*) DATA, integer, dimension(*) START, integer, dimension(*) SIZE)
Definition at line 338 of file napif.f.
References nxgetinfo().
Referenced by __napif_test.f__().
LOGICAL function nxsameid (integer, dimension(*) FILEID, integer, dimension(*) LINK1, integer, dimension(*) LINK2)
Definition at line 444 of file napif.f.
Referenced by __napif_test.f__().
INTEGER function nxsetnumberformat (integer, dimension(*) FILEID, integer ITYPE, character*(*) FORMAT)
Definition at line 226 of file napif.f.
References extract_string().
subroutine replace_string (character*(*) STRING, integer*1, dimension(*) ISTRING)
Convert NULL terminated C string ISTRING to FORTRAN string STRING.
Definition at line 101 of file napif.f.
Referenced by nxgetcharattr(), nxgetchardata(), nxgetgroupinfo(), nxgetnextattr(), nxgetnextentry(), nxgetpath(), nxinquirefile(), and nxisexternalgroup().
INTEGER function truelen (character*(*) STRING)
Return length of a string, ignoring trailing blanks.
Definition at line 69 of file napif.f.
Referenced by extract_string().