NeXus: bindings/f77/napif_test.f File Reference
napif_test.f File Reference
Functions/Subroutines
program __napif_test.f__
Function/Subroutine Documentation
program __napif_test.f__ ()
Definition at line 28 of file napif_test.f.
References nxclose(), nxclosedata(), nxclosegroup(), nxcompmakedata(), nxflush(), nxgetattr(), nxgetattrinfo(), nxgetcharattr(), nxgetchardata(), nxgetdata(), nxgetdataid(), nxgetgroupid(), nxgetgroupinfo(), nxgetinfo(), nxgetnextattr(), nxgetnextentry(), nxgetslab(), nxmakedata(), nxmakegroup(), nxmakelink(), nxopen(), nxopendata(), nxopengroup(), nxopenpath(), nxputattr(), nxputcharattr(), nxputchardata(), nxputdata(), nxputslab(), and nxsameid().